### ISSUE TITLE
CoreFx builds failing with undeclared identifier - CURLM_ADDED_ALREADY

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#4288]
I've just started this failure in CoreFx builds on CentOS 7.1.1503

This is with libcurl version 7.29.0

See PR #4267

2015-11-02T18:00:27.683Z: [ 12%] Building C object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/openssl.c.o
 2015-11-02T18:00:27.772Z: error: use of undeclared identifier 'CURLM_ADDED_ALREADY'; did you mean 'PAL_CURLM_ADDED_ALREADY'?
 2015-11-02T18:00:27.772Z: static_assert(PAL_CURLM_ADDED_ALREADY == CURLM_ADDED_ALREADY, "");
 2015-11-02T18:00:27.773Z: ^~~~~~~~~~~~~~~~~~~
 2015-11-02T18:00:27.773Z: PAL_CURLM_ADDED_ALREADY
 2015-11-02T18:00:27.773Z: /root/corefx/src/Native/System.Net.Http.Native/pal_multi.h:19:5: note: 'PAL_CURLM_ADDED_ALREADY' declared here
 2015-11-02T18:00:27.773Z: PAL_CURLM_ADDED_ALREADY = 7,
 2015-11-02T18:00:27.773Z: ^
 2015-11-02T18:00:27.780Z: 1 error generated.
 2015-11-02T18:00:27.782Z: make[2]: *** [System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/pal_multi.cpp.o] Error 1

**Comment by eerhardt** [comment]
This error happens because the CURLM_ADDED_ALREADY constant was added in libcurl version 7.32, so it wasn't available in v7.29.

libcurl version 7.29.0 is 2.5 years old ([released Feb 6 2013](http://curl.haxx.se/changes.html)). Is that the latest version available for CentOS?

**Comment by chcosta** [comment]
I upgraded the CentOS docker image the CI is using of libcurl to v7.45, and builds are now passing again.  Thanks!
