### PR TITLE
Specify Xunit.PlatformID where ambiguous in dev/api tests

### PR DESCRIPTION
**Pull request by dagood**
When the build pipeline runs `build-tests.cmd` for the dev/api branch it hits these errors (taken from one leg, but they appear to all be the same):

```
BasicEventSourceTest\TestsEventSourceLifetime.cs(23,27): error CS0104: 'PlatformID' is an ambiguous reference between 'System.PlatformID' and 'Xunit.PlatformID' [D:\A\_work\3\s\src\System.Diagnostics.Tracing\tests\System.Diagnostics.Tracing.Tests.csproj]
System\Threading\WaitHandleTests.cs(87,38): error CS0117: 'PlatformID' does not contain a definition for 'Windows' [D:\A\_work\3\s\src\System.Runtime\tests\System.Runtime.Tests.csproj]
System\GCTests.cs(401,38): error CS0117: 'PlatformID' does not contain a definition for 'Windows' [D:\A\_work\3\s\src\System.Runtime\tests\System.Runtime.Tests.csproj]
System\TimeZoneInfoTests.cs(1674,38): error CS0117: 'PlatformID' does not contain a definition for 'AnyUnix' [D:\A\_work\3\s\src\System.Runtime\tests\System.Runtime.Tests.csproj]
System\TimeZoneInfoTests.cs(1697,38): error CS0117: 'PlatformID' does not contain a definition for 'AnyUnix' [D:\A\_work\3\s\src\System.Runtime\tests\System.Runtime.Tests.csproj]
System\TimeZoneInfoTests.cs(1721,38): error CS0117: 'PlatformID' does not contain a definition for 'AnyUnix' [D:\A\_work\3\s\src\System.Runtime\tests\System.Runtime.Tests.csproj]
System\TimeZoneInfoTests.cs(1838,38): error CS0117: 'PlatformID' does not contain a definition for 'AnyUnix' [D:\A\_work\3\s\src\System.Runtime\tests\System.Runtime.Tests.csproj]
```

`System.PlatformID` was introduced in https://github.com/dotnet/corefx/pull/9851, and some references to `Xunit.PlatformID` were changed to explicitly reference the xunit one, but not these. I haven't been able to track down yet why this error happens in the pipeline but not CI or local builds.

There are many build-tests legs in the pipeline so I'm working on confirming that these are the only ambiguous references.

/cc @danmosemsft @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by dagood** [comment]
I went through the build legs and the errors are all the same.

**Comment by dagood** [comment]
It looks like those ARM emulator tests are flaky--failures have happened in other PRs too: `umount: /opt/linux-arm-emulator-root/dev: device is busy.`. Everything else passed, so merging.
