### ISSUE TITLE
Problem installing System.Net.NetworkInformation in a project targeting dnxcore50

### ISSUE THREAD

**Issue by Nitinr5** [dotnet/corefx#7473]
Hi

I'm trying to run a simple code to print Hostname using static class Dns.(using System.Net)
                /*string HostName = Dns.GetHostName();
                Console.WriteLine("Host Name of machine =" + HostName);*/

This runs fine on VS 2015 and moreover **assembly portability analyser claims that it's 100%  portable to dot NetCore 5.0.**
However, DNX on Ubuntu 14.04 fails to run it with following error.

**error CS0103: The name 'Dns' does not exist in the current context**
Note: Its the same code as ran on VS2015. I just ported it to ubuntu. It's not a programming error.

Is the location of Dns changed or its just not supported in latest DNX?

I've noticed a **similar behaviour for class NetworkInterface** which also **depends on system.dll** assembly. Again, the **porting tool reported that code is 100% portable**, but it actually failed in compilation with following error.
**error CS0246: The type or namespace name 'NetworkInterface' could not be found (are you missing a using directive or an assembly reference?)**

I've checked the project.lock.json file for the linux project and there was no mention of System.dll in it. However the same was present as References in VS 2015.

Please let me know if I'm missing something.
Regards

**Comment by svick** [comment]
`Dns` is in the `System.Net.NameResolution` package, `NetworkInterface` is in the `System.Net.NetworkInformation` package. Have you added those to your `project.json`?

**Comment by Nitinr5** [comment]
thanks for your input.
I was able to use Dns after including NameResolution as dependency. However, networkinformation dependency is failing with this error.
**    Unable to resolve System.Net.NetworkInformation (>= 4.1.0-rc2-23811) for DNXCore,Version=v5.0 (ubuntu.14.04-x64).
    Unable to resolve runtime.linux.System.Net.NetworkInformation (>= 4.1.0-rc2-23811) for DNXCore,Version=v5.0 (ubuntu.14.04-x64).**

am I missing something ?

**Comment by davidsh** [comment]
cc: @ericstj

**Comment by svick** [comment]
For me, it works with `netstandardapp1.5`, but with `dnxcore50` I get a similar error:

> System.Net.NetworkInformation 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Net.NetworkInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.10-x64.

**Comment by ericstj** [comment]
Can you guys use the latest bits, both packages and CLI and see if there is any issue?  You can get the latest packages from https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.  If you're still hitting restore issues share a project.lock.json via gist.

**Comment by svick** [comment]
I still get the same issue with latest CLI from the repository listed in Getting started (though it seems to be somewhat old: 1.0.0-beta-001793) and latest package from MyGet (4.1.0-rc3-23910).

My commands:

```bash
$ sudo apt-get update
$ sudo apt-get install dotnet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dotnet is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 348 not to upgrade.
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001793)

Product Information:
 Version:     1.0.0-beta-001793
 Commit Sha:  42a0eec967

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.10
 OS Platform: Linux
 Runtime Id:  ubuntu.14.10-x64
$ dotnet new
Created new C# project in /home/osboxes/hwapp.
$ vi project.json 
$ dotnet restore
```

The error I get:

> error: System.Net.NetworkInformation 4.1.0-rc3-23910 provides a compile-time reference assembly for System.Net.NetworkInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.10-x64.

[My `project.json` and `project.lock.json`.](https://gist.github.com/svick/75dec1285d9b069ff18964510a0c8178)

**Comment by ericstj** [comment]
A couple problems here: 
- you need to bring in the RID graph from MS.NETCore.Platforms.  Without it NuGet knows nothing about what ubuntu.14.10-x64 means.  When you first did `dotnet new` you would have had a package reference that brought this in but you deleted it.
- 23910 isn't newest; that's still a month old.  newest is 4.1.0-rc3-24005-00.

**Comment by ericstj** [comment]
Oh, and the version of CLI is still very old  they're on beta-002222 right now.

**Comment by svick** [comment]
@ericstj 

> you need to bring in the RID graph from MS.NETCore.Platforms. Without it NuGet knows nothing about what ubuntu.14.10-x64 means. When you first did dotnet new you would have had a package reference that brought this in but you deleted it.

Yes, I did. Because of the name, I assumed that was `netstandardapp`-specific. If I add it the dependency to `NETStandard.Library` back, everything works fine. Sorry about that.

> 23910 isn't newest; that's still a month old. newest is 4.1.0-rc3-24005-00.

You're right. I was looking at `runtime.linux.System.Net.NetworkInformation` by mistake in the MyGet listing, to find the latest version.

> Oh, and the version of CLI is still very old they're on beta-002222 right now.

That's the version `apt-get` is giving me. Am I doing something wrong?

I don't know how `apt-get` works, but browsing through http://apt-mo.trafficmanager.net/repos/dotnet/, I see 1.0.0.001793 as the latest version of `dotnet`. I also see package named `dotnet-dev-1.0.0-beta-002222` but that's `dotnet-dev`, not `dotnet` and it also seems to have version number as part of the package name, which I've never seen before. Am I really supposed to be doing `sudo apt-get install dotnet-dev-1.0.0-beta-002224`?

If I do that, I get a new error from `dotnet build`:

> Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'ubuntu.14.10-x64'.

My commands:

```
$ sudo apt-get install dotnet-dev-1.0.0-beta-002224
$ dotnet --version
1.0.0-beta-002224
$ dotnet restore
$ dotnet build
```

**Comment by mellinoe** [comment]
@svick With newer versions of the CLI, I believe you should no longer use "dnxcore50". Instead, use `netstandard` or `netstandardapp`. @ericstj , does that sound correct?

**Comment by ericstj** [comment]
@svick it'd be good to update the boilerplate portion of your project.json to match what you get from dotnet new.  A lot of things have changed recently WRT shared framework and frameworks as @mellinoe mentioned.

**Comment by ericstj** [comment]
The following works fine for me using the sample code provided and the latest CLI:
```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002306"
    },
    "System.Net.NetworkInformation": "4.1.0-rc2-23931"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by softlion** [comment]
Hey, i'm using a netstandard 1.3 portable library using the System.Net.NetworkInformation package, in a .NET Framework 4.6.1 console app using packages.config

It compiles fine and runs until it hits a type in networkinformation. At this point an exception occurs "could not find System.Net.NetworkInformation assembly".

As the console project does not use project.json, is there a way to make this working ?
