### ISSUE TITLE
Question: how does targeting netstandard versus netcoreapp work?

### ISSUE THREAD

**Issue by polarapfel** [dotnet/corefx#18217]
Hi,

I'm not sure I'm asking in the right place.

I have a question regarding targeting. I created new console app using `dotnet new console`.

Now, the project file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
</Project>
```

Can I target `netstandard1.6` instead? Will it still run?

Changing the project file to:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
</Project>
```
This builds using `dotnet build`. It doesn't run however.

```
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Exe'.
```

Is targeting .NET Standard only for libraries, not for executable binaries? I was hoping I could target a standard instead of any runtime and then choose a runtime of my liking to run that binary, as long as that runtime supports that standard version. Like choosing to either point `dotnet` or `mono` against a binary that targets netstandard. Is this even possible?

And speaking of `OutputType` Exe, even in the original console project template, the build drops a dll, not an exe. Why is that?

thanks,

Tobias W.

**Comment by davidsh** [comment]
This might be helpful as it talks about NETStandard:
https://github.com/dotnet/standard/blob/master/docs/faq.md

cc; @ericstj

**Comment by polarapfel** [comment]
Hi @davidsh,

thanks for the link. I've been through that already, it doesn't help me understand as to my specific question.

I understand how this affects when building a _**library**_ and targeting `netstandard` there. So far so good. A library targeting `netstandard` can be referenced from its assembly across .NET solutions targeting different runtimes as long as all of them support the same API surface described by the standard.

But I don't understand if targeting `netstandard` for an _**executable**_ project type is supported or not. It doesn't seem to be. But what good is a standard across runtimes, when I still have to create various project templates against each runtime supporting the same standard and API surface to begin with? Why can't I just have one executable project definition, targeting a standard and any runtime with a standard compliant framework behind it will then run it?

By the way, the particular issue with how dotnet treats a project targeting netstandard seems to be related to how it's packaged and how the CLR handles the binary. Pointing dotnet to the dll renders:

```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/mnt/c/Users/tobiaw/Source/Repos/AzTools/AzTools/azcd/bin/Debug/netstandard1.6'.
```

The same executes just fine when pointing the latest mono runtime at the same binary.

--

In essence, I was hoping .NET Standard would deliver the promise that Java made its developers a long time ago: Write once, run anywhere. Any Java bytecode compiled by any compliant runtime runs on any other Java runtime as long as they support the same Java version.

So really, only non-executable libraries benefit from .NET Standard, executables don't. Am I wrong here?

**Comment by davidsh** [comment]
@ericstj and @weshaggard are the experts here...so it would be best for them to help answer your questions.

**Comment by ViktorHofer** [comment]
When you compile a .NET Standard library it will build against netstandard.dll which is only a reference assembly and does nothing more than TypeForwarding to the actual implementation inside netfx, netcoreapp or mono. Therefore a .NET Standard Library can't be an executable file because the actual implementation is missing.

@terrajobst: Please correct me if I'm wrong.

**Comment by danmosemsft** [comment]
Is the exe part the confusion? See https://github.com/dotnet/cli/issues/6237

**Comment by polarapfel** [comment]
@danmosemsft Thanks for linking that, that was part of the confusion, though not the critical part. Seems like the "--self-contained" option is in 2.0, not 1.1 yet. Thanks!

**Comment by polarapfel** [comment]
@ViktorHofer If that's the case, mono shouldn't be able to execute the project after compiling it against netstandard1.6 instead of netcoreapp1.1, right? That works however.

My underlying misconception evolves around:

What's the best way to build an executable binary that is runtime agnostic? My thought was: targeting netstandard with the assumption that any runtime/framework configuration compliant with that netstandard version will be able to run that binary. Doesn't seem to be the case.

Specifically, what's currently the best way to work with the dotnet toolchain when I want to remain within the netstandard 1.6.1 API surface but distribute and run resulting binaries on both netcore and mono?

**Comment by ViktorHofer** [comment]
Mono can execute a library which targets and builds against netstandard1.6? That's seems weird to me. A .NET Standard Library doesn't have any application entry point (Program.Main) so what would it execute? I'm really curious about that.

> What's the best way to build an executable binary that is runtime agnostic?

**Framework-dependent deployment (FDD)**. _You do not have to define the target operating systems that your .NET Core app will run on in advance. Because .NET Core uses a common PE file format for executables and libraries regardless of operating system, .NET Core can execute your app regardless of the underlying operating system. For more information on the PE file format, see .NET Assembly File Format._

Then you can execute your application with "dotnet <path to app dll>". Please don't get confused that it does not contain an ".exe" file, the "[appname].dll" is still **executable**.

From here: https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/

**Comment by polarapfel** [comment]
Hi @ViktorHofer,

Create a new console app: dotnet new console

This template has a single C# file with a main that prints Hello World to the console.

Change the TargetFramework from netcoreapp1.1 to netstandard1.6. Restore packages and build.

The build works without issues.

This binary won't run with dotnet however.

Point mono to the dll and you'll see main executing, outputting Hello World to the console.

I ran a hex diff against the dll when built against netstandard1.6 and netcoreapp1.1. There is almost no difference in the binaries, byte by byte. Apart from around ~100 bytes, the files are identical and have the same size. Main certainly is in both. Just when running dotnet against the netstandard binary, it complains there's no hostpolicy assembly.

**Comment by ericstj** [comment]
Portable (netstandard) EXEs is something we've talked about in the past but never really scoped in. /cc @blackdwarf @terrajobst @davidfowl @Petermarcu 

Currently the .NETCore host has some requirements that should probably have better defaults to enable hacking this scenario.  There are also some roadblocks in the SDK like you mentioned.

Here's what I tried:
```
dotnet new console
<change to netstandard2.0>
dotnet build
dotnet bin\Debug\netstandard2.0\myapp.dll
```

That gave me:
```
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'F:\nsapp\bin\Debug\netstandard2.0\'.
```

I suspect there are some arguments you can specify to make this work.  @gkhanna79 would know better.  If you want to find out for yourself you can also look at https://github.com/dotnet/core-setup/blob/3089d7a55442551e53d13a422156ae0a458e9c64/src/corehost/cli/fxr/fx_muxer.cpp#L868.  Also enabling the host tracing is interesting to see what its doing (set COREHOST_TRACE=true).

I suspect it has trouble if its missing a runtimeconfig and/or deps file.  If its important to enable, file an issue in https://github.com/dotnet/core-setup.  That could put it on par with Mono and desktop.  In both of those frameworks you can activate a exe (potentially through a host) and it'll try to run the IL using assemblies next to the EXE and some central location (GAC/Framework directory).  Once everyone supports ns2.0 this will provide a good amount of surface area for a portable exe that just works without dependencies.

The problem comes if you have any dependencies.  Suppose one of those dependencies needs to be different per framework, or per OS.  There isn't any agreed upon convention to represent application binaries in that way across frameworks.  If we really wanted to make this work we'd have to get all .NET runtimes to agree upon how to locate framework and runtime specific assets at runtime.  .NET Core does this already for runtime specific assemblies: that's what its using the deps file for, but not for framework specific assemblies.  One could conceivably implement and assembly load scheme at the application layer that would make this work, but those sorts of things always sound good and simple in principal and get hairy when you try to actually build them.  To do this right and complete we'd probably want to do it at the framework level.

**Comment by polarapfel** [comment]
@ericstj 

> There isn't any agreed upon convention to represent application binaries in that way across frameworks.

That's the key point indeed. In my humble opinion, the usefulness of .NET Standard being applicable not just to a single, non-executable library assembly but also to the ability to package executable applications against a standard would really help though, so extending the standard by such a convention might not be a bad idea. It would also put .NET on par with how Java solved this problem (well, they've never been as fragmented as the .NET platform to begin with...).

**Comment by gkhanna79** [comment]
Hostpolicy.dll is expected to be in the app folder when it is determined that the application is being built is standalone. Is that not the case (for standalone apps, runtimeconfig.json also does not carry FX details).

CC @ramarag who owns the host.

**Comment by andycmaj** [comment]
interesting case i ran into RE `netstandard` vs `netcoreapp`.

here's a code snippet:

```csharp
        public override HttpMessageHandler CreateMessageHandler()
        {
            if (config.MarketingApiDisableSslCertValidation)
            {
                return new HttpClientHandler
                {
                    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
                };
            }

            return base.CreateMessageHandler();
        }
```

when the csproj has `    <TargetFramework>netstandard2.0</TargetFramework>`, this fails.

```
Common/MarketingApiFlurlClient.cs(70,83): error CS0117: 'HttpClientHandler' does not contain a definition for 'DangerousAcceptAnyServerCertificateValidator' [/Workspace/ims/TheChunnel/activities/TheChunnel.Activities.Marketing/TheChunnel.Activities.Marketing.csproj]
```

i noticed the same snippet was working in a `netcoreapp2.0` project so i changed this project to `netcoreapp2.0` and viola, dotnet can find the correct API i was referencing.

when i look at the assembly `HttpClientHandler` is coming from in the 2 cases (Left: `netcoreapp2.0` project, Right: `netstandard2.0` project), here's what i see:
<img width="1920" alt="screencapture at fri jan 19 19 03 51 pst 2018" src="https://user-images.githubusercontent.com/97470/35179262-a901c7e2-fd4b-11e7-9371-4e8cd9fbbc48.png">

in the `netcoreapp2.0` case, it's using `Assembly System.Net.Http, Version=4.2.0.0` and in the `netstandard2.0` case, `Assembly netstandard, Version=2.0.0.0`.

i know i am probably doing something wrong here, but i don't get why `netstandard` has a smaller set of reference APIs than `netcoreapp2.0`. i thought the difference was in "library" project vs "executable application".

Can someone explain this difference? I think it's relevant to this topic.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
There are plenty of articles and explanations on internet - in nutshell standard is a standard (like HTML is a standard) - it is the common API surface for 4 platforms (think browsers as implementations of HTML standard): .NET Core, .NET Framework, UWP and Mono. Each platform can have more APIs than just the standard - like in your case [`HttpClientHandler.DangerousAcceptAnyServerCertificateValidator`](https://apisof.net/catalog/System.Net.Http.HttpClientHandler.DangerousAcceptAnyServerCertificateValidator).

To learn more, search internet for "[.NET Standard vs. .NET Core"](https://www.bing.com/search?q=net+standard+vs+net+core&qs=SC&pq=netstandard+vs+.net+core&sc=2-24&cvid=C220DD0956E14F16B5C2EDCA86065E90&FORM=QBRE&sp=1) - you can start with [.NET blog post](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) on the topic.

**Comment by andycmaj** [comment]
FWIW, @karelz, most of the articles i've tried to read on netstandard are very theoretical with lots of historical context about WHY netstandard (and often a bit dated with respect to the actual latest dotnet versions, and not much practical advice/concrete examples like the one i posted above. 

https://dotnetcore.gaprogman.com/2016/11/24/net-standard-what-it-is-and-how-it-applies-to-net-core/

https://dotnetcoretutorials.com/2017/01/13/net-standard-vs-net-core-whats-difference/

https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7

https://stackoverflow.com/questions/36962930/whats-the-difference-between-the-new-netstandardapp-and-netcoreapp-tfms

After i noticed this difference, it made more sense to me on an intuitive level what the differences are here...

I also remember articles back in v1.x that recommended that executables target `netcoreapp` and libraries target `netstandard`.

This may still be true, but it isn't the full story. in my example, i have a bunch of "library" projects that are really just ways to structure my application for the purposes of organization, dependency management, service boundaries, etc. In my case, i still NEED to make my "libraries" target `netcoreapp` unless i want to refactor my application. the old "you should re-examine your design" argument. Which may be true, but it wasn't really clear WHY until i found an API that isn't part of the Standard, but is part of a platform.

All i'm really saying here is that the documentation available is not super helpful. official articles like https://docs.microsoft.com/en-us/dotnet/core/packages (which is helpful, but again a bit out of date) aren't actually even in top google search results for "netstandard vs netcoreapp", and the fact that there are so many SO questions/blog posts trying to explain this might hint at a lack of official, practical documentation/examples here. Might just be a case of code outpacing docs, but that's not great.

**Comment by Petermarcu** [comment]
@andycmaj thanks for the feedback.

@terrajobst , whats the best place to track this and the creation of a clear document about making this choice? In its simplest form, .NET Standard is what you should use if you want your library to be shareable across the maximum set of .NET Platforms. If you are intending to publish a general purpose reusable library to NuGet, for example, ideally you can target .NET Standard so people can use it in the most places. 

If you are only targeting a single platform and just using libraries as architectural or implementation details of your application or just sharing between multiple applications that target the same .NET platform, there isn't much value in targeting .NET Standard other than "future proofing" in case you ever do want to move to another .NET Platform.

**Comment by mika76** [comment]
_(I posted an SO question [here](https://stackoverflow.com/questions/48822040/running-net-standard-binaries-on-different-framrworks?noredirect=1#comment84652399_48822040) and a comment directed me to this issue)_

I think the distinction that .net standard is only for class libraries and not executables (at least not yet re [comment](https://github.com/dotnet/corefx/issues/18217#issuecomment-293668929) from @ericstj) should really be more distinct in the documentation and FAQ. 

Looking at the .net standard docs and the faq there really seems to be no mention of it, and it's not nearly as logical as people seem to think. 

If we look at the FAQ https://github.com/dotnet/standard/blob/master/docs/faq.md#what-is-net-standard there is no mention this is only for class libraries.

The only mention I see now is in the blog post at https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/ in the "Why do we need a standard?" section:

> **Applications.** In the context of applications you don’t use .NET Standard directly. However, you still benefit indirectly. First of all, .NET Standard makes sure that all .NET platforms share the same API shape for the base class library. Once you learn how to use it in your desktop application you know how to use it in your mobile application or your cloud service. Secondly, with .NET Standard most class libraries will become available everywhere, which means the consistency at the base layer will also apply to the larger .NET library ecosystem.

But reading though it seems pretty ambiguous to me. It does not mention that **executables** can not be run as netstandard, but **applications** which could mean a whole lot more conceptually than executables. I only now understand what it means having some context.

**Comment by jnm2** [comment]
Executables and tests, at least until we finally get .NET Standard tests: https://github.com/dotnet/sdk/issues/1561
