### ISSUE TITLE
Clean build produces several MSB3245 "netstandard" warnings

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16108]
When I do a clean build, I get several warnings like the following:
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "netstandard". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\stoub\Source\repos\corefx\src\Tools\CoreFx.Tools\CoreFx.Tools.csproj]
```
cc: @weshaggard

**Comment by weshaggard** [comment]
CoreFxTools is a temporary thing but I agree it would be nice to be warning free.

**Comment by weshaggard** [comment]
I'm not entirely sure what fixed this but I don't see the build warning any longer.

cc @ericstj

**Comment by ericstj** [comment]
@weshaggard you regressed this with https://github.com/dotnet/corefx/commit/6cb8c638f4d49b8f723c8012707c1dca57dadd54#diff-53c14936ddb0a4adc94bcde1ec388167L71 and I fixed it with https://github.com/dotnet/corefx/commit/87e1262bd0e66513c729d0be06f3d76e05d599b1#diff-53c14936ddb0a4adc94bcde1ec388167R65
