### ISSUE TITLE
Enlisting in Ambient transactions is not supported

### ISSUE THREAD

**Issue by upendra22** [dotnet/corefx#24282]
using (TransactionScope scope = new TransactionScope(TransactionScopeOption.RequiresNew))
                {
                    SqlCommand cmd = new SqlCommand("ProcedureName", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("Name", "upendra");
                    cmd.Parameters.AddWithValue("EmailId", "a@a.com");
                    cmd.Parameters.AddWithValue("MobileNumber", "384747848");
                    con.Open();
                    cmd.ExecuteNonQuery();
                    scope.Complete();
                }
**Error: Enlisting in Ambient transactions is not supported**

**Comment by stephentoub** [comment]
This was implemented in https://github.com/dotnet/corefx/pull/22059.

**Comment by upendra22** [comment]
I am getting exception in .net core 2.0 and System.Data.SqlClient v4.4.0

**Comment by stephentoub** [comment]
That change is not in .NET Core 2.0.  It's in the master branch for the next release.

**Comment by grandchamp** [comment]
It's on daily builds?

**Comment by stephentoub** [comment]
Yes.

**Comment by grandchamp** [comment]
Maybe i'm getting wrong, but https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient last update was 22 days ago.

**Comment by danmosemsft** [comment]
@grandchamp ignore the "preview2" packages. This was a temporary glitch. The latest at the moment is https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient/4.5.0-preview1-25729-02

**Comment by saurabh500** [comment]
Fixed with https://github.com/dotnet/corefx/pull/22059

**Comment by evil-shrike** [comment]
There's an interesting point here. 

On System.Data.SqlClient v4.3.0 opening an SqlConnection inside `TransactionScope` or with set `Transaction.Current` works. Transaction isn't distributed of cause, but SqlClient doesn't throw. It works in the same way as without `TransactionScope`.

On the contrary on System.Data.SqlClient v4.4.0 opening an SqlConnection in the same conditions throws System.NotSupportedException: "Enlisting in Ambient transactions is not supported".

So code ported from netfx worked on 4.3 but starts failing on 4.4.

**Comment by stu-mck** [comment]
Any update on when 4.5 will be available for general consumption? Transaction management is becoming a blocker for us.

**Comment by y-vasilyev** [comment]
Is there any idea about workaround? Any help is higly appreciated, it blocks my work too :(

**Comment by y-vasilyev** [comment]
@stu-mck I solved this issue in my project, here is my workaround for this problem - https://stackoverflow.com/questions/47421371/dapper-is-throwing-system-data-sqlclient-sqlconnection-exception-after-upgrading/48273860#48273860
based on @evil-shrike  comment

**Comment by tempywritescode** [comment]
Please reopen this issue, it's a blocker over here too and there's no satisfactory workaround afaik.

**Comment by mikeloguay** [comment]
We have the same issue. We are starting a class library targeting .NET Standard 2.0. We faced the "Ambient transactions is not supported", so we tried the workaround of downgrade the version of System.Data.SqlClient to 4.3.x, but this cause the following build error:

`Folder\Class.cs(9,75): error CS0433: The type 'SqlDbType' exists in both 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [C:\Path\MyProject.csproj]`

In "MyProject", we have the following dependencies:

```
<PackageReference Include="log4net" Version="2.0.8" />
<PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
<PackageReference Include="System.Data.SqlClient" Version="4.3.1" />
```

We tried with several versions of System.Data.SqlClient with no success.

Any clue? Please help, because I cannot wait to Q2 2018 for the patch, and I would not like to use the other workaround proposed: use explicit transaction model.

Many thanks in advance.

**Comment by edaloicaro18** [comment]
@mikeloguay I tried all the suggested workarounds and none of them worked.
In the end I had to use the explicit model (BeginTransaction/Commit) :(

**Comment by matthewblott** [comment]
This is still an issue. I've also tried all the workarounds suggested here with no success.

**Comment by liesbethvandevenne** [comment]
I have the same issue.

**Comment by jeinz11** [comment]
When will this be fixed? its a serious blocker for us :(

**Comment by saurabh500** [comment]
This is now supported on the 4.5 preview build of SqClient available on Nuget

**Comment by jeinz11** [comment]
thanks @saurabh500

**Comment by olkuziv** [comment]
Thanks, i was update System.Data.Sql and Dapper start using this)
