### ISSUE TITLE
System.Security.Cryptography.Native OSX build errors.

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#8716]
My native build on OSX is failing from some compilation errors in the native crypto library. The failures look to be introduced by https://github.com/dotnet/corefx/pull/8600.

```
Scanning dependencies of target System.Security.Cryptography.Native
[ 66%] [ 67%] [ 69%] [ 70%] [ 72%] Building CXX object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_ecc_import_export.cpp.o
Building CXX object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_hmac.cpp.o
Building CXX object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_ssl.cpp.o
Building CXX object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_x509ext.cpp.o
Building CXX object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_x509_root.cpp.o
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_ecc_import_export.cpp:351:14: error: use of undeclared identifier 'EC_KEY_set_public_key_affine_coordinates'
        if (!EC_KEY_set_public_key_affine_coordinates(*key, qxBn, qyBn))
             ^
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_ecc_import_export.cpp:493:14: error: use of undeclared identifier 'EC_KEY_set_public_key_affine_coordinates'
        if (!EC_KEY_set_public_key_affine_coordinates(key, qxBn, qyBn))
             ^
2 errors generated.
make[2]: *** [System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_ecc_import_export.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_ssl.cpp:80:34: error: use of undeclared identifier 'SSL_OP_NO_COMPRESSION'
        SSL_CTX_set_options(ctx, SSL_OP_NO_COMPRESSION);
                                 ^
/usr/include/openssl/ssl.h:582:39: note: expanded from macro 'SSL_CTX_set_options'
        SSL_CTX_ctrl((ctx),SSL_CTRL_OPTIONS,(op),NULL)
                                             ^
1 error generated.
make[2]: *** [System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_ssl.cpp.o] Error 1
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_hmac.cpp:33:9: error: cannot initialize a variable of type 'int' with an rvalue of type 'void'
    int ret = HMAC_Init_ex(ctx.get(), key, keyLen, md, nullptr);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_hmac.cpp:56:12: error: cannot initialize return object of type 'int32_t' (aka 'int') with an rvalue of type 'void'
    return HMAC_Init_ex(ctx, nullptr, 0, nullptr, nullptr);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_hmac.cpp:70:12: error: cannot initialize return object of type 'int32_t' (aka 'int') with an rvalue of type 'void'
    return HMAC_Update(ctx, data, UnsignedCast(len));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bryan/git/corefx/src/Native/System.Security.Cryptography.Native/pal_hmac.cpp:86:9: error: cannot initialize a variable of type 'int' with an rvalue of type 'void'
    int ret = HMAC_Final(ctx, md, &unsignedLen);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
make[2]: *** [System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_hmac.cpp.o] Error 1
make[1]: *** [System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/all] Error 2
```

This is on a fresh clone of the CoreFX repo.

@steveharter @bartonjs

**Comment by ianhays** [comment]
My bad, it's actually my OSX machine this is failing on.

**Comment by steveharter** [comment]
Hmm can you try to get a later version of openssl, or re-run link... FWIW that API existed in much earlier versions so not sure.

brew install openssl
brew link --force openssl

**Comment by steveharter** [comment]
may have to enter brew unlink openssl

**Comment by ianhays** [comment]
Tried the above. Now I get:

```
Linking CXX shared library System.Security.Cryptography.Native.dylib
Undefined symbols for architecture x86_64:
  "_EC_KEY_set_public_key_affine_coordinates", referenced from:
      _CryptoNative_EcKeyCreateByKeyParameters in pal_ecc_import_export.cpp.o
      _CryptoNative_EcKeyCreateByExplicitParameters in pal_ecc_import_export.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [System.Security.Cryptography.Native/System.Security.Cryptography.Native.dylib] Error 1
make[1]: *** [System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/all] Error 2

```

**Comment by steveharter** [comment]
If you've ran:
   brew link --force openssl
and did a clean build not sure. I just compiled this yesterday on my mac and I believe I got some similar errors that were cleaned up by re-link

**Comment by ianhays** [comment]
>and did a clean build 

That was my issue. A ```clean.sh``` resolved the failures. Thanks!
