### PR TITLE
 System.Security.Cryptography.Pkcs. Refactor DllImports

### PR DESCRIPTION
**Pull request by Marusyk**
Issue #33774

Should I also move all SafeHandles from `System.Security.Cryptography.Pkcs\src\Microsoft\Win32\SafeHandles` to `Common\src\Microsoft\Win32\SafeHandles`

Please review

### CODE REVIEW

File: src/Common/src/Interop/Windows/kernel32/Interop.Heap.cs [hunk 1]
```diff
@@ -3,15 +3,12 @@
...
-
 using Microsoft.Win32.SafeHandles;
 
-internal static partial class Interop
+internal partial class Interop
 {
-    internal static partial class Heap
+    internal partial class Kernel32
     {
         [DllImport(Libraries.Kernel32, CharSet = CharSet.Unicode, SetLastError = true)]
```
Comment (jkotas) [inline src/Common/src/Interop/Windows/kernel32/Interop.Heap.cs]: SetLastError on methods in this file is unnecessary overhead - none of the callers check the last error.

File: src/Common/src/Interop/Windows/Crypt32/Interop.CertDuplicateCertificateContext.cs [hunk 2]
```diff
@@ -4,13 +4,12 @@
...
-using System.Security.Cryptography.X509Certificates;
 
 internal static partial class Interop
 {
     internal static partial class Crypt32
     {
-        [DllImport(Interop.Libraries.Crypt32, CharSet = CharSet.Unicode, SetLastError = true)]
-        internal static extern SafeCertContextHandle CertDuplicateCertificateContext(IntPtr pCertContext);
+        [DllImport(Libraries.Crypt32, CharSet = CharSet.Unicode, SetLastError = true)]
+        internal static extern IntPtr CertDuplicateCertificateContext(IntPtr pCertContext);
```
Comment (bartonjs) [inline src/Common/src/Interop/Windows/Crypt32/Interop.CertDuplicateCertificateContext.cs]: > 17:41:07 System\Security\Cryptography\X509Certificates\X509Utils.cs(16,53): error CS0029: Cannot implicitly convert type 'System.IntPtr' to 'System.Security.Cryptography.X509Certificates.SafeCertContextHandle' [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Windows.Extensions\src\System.Windows.Extensions.csproj]

This is a bad change.  The PKCS caller of this presumably is calling into a function that will automatically free the certificate context; which means that there are three different fixes:

1) The PKCS caller gets this into a SafeHandle, saves the handle (DangerousGetHandle()) then calls SetInvalid to prevent the SafeHandle from doing cleanup.

2) Add CertDuplicateCertificateContext_NoSafeHandle to return the IntPtr, change PKCS to call that (which then sets DllImportAttribute.EntryPoint as "CertDuplicateCertificateContext").

3) Leave this one alone, as the PKCS caller is doing "something weird" that doesn't belong in common src.

Comment (Marusyk) [reply src/Common/src/Interop/Windows/Crypt32/Interop.CertDuplicateCertificateContext.cs]: I have problems with the second case. I'm not sure that I know how to implement the first one. So, I prepared a change for the third one
