### PR TITLE
Trivial update WindowsRuntimeResourceManager

### PR DESCRIPTION
**Pull request by luqunl**
Update PRIExceptionInfo field's name caused by https://github.com/dotnet/coreclr/pull/18417

### CODE REVIEW

**Comment by tarekgh** [comment]
@luqunl I marked this issue as no-merge till we get the update from coreclr

**Comment by luqunl** [comment]
The change "Remove Opcodes due to Opcodes moved to S.P.Corelib" is to solve duplicate OpCode type issue. 

11:44:48 System\Reflection\Emit\OpCodes.cs(981,32): error CS0436: The type 'OpCode' in 'D:\j\workspace\windows-TGrou---c60886e1\src\System.Reflection.Primitives\src\System\Reflection\Emit\Opcode.cs' conflicts with the imported type 'OpCode' in 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Using the type defined in 'D:\j\workspace\windows-TGrou---c60886e1\src\System.Reflection.Primitives\src\System\Reflection\Emit\Opcode.cs'. [D:\j\workspace\windows-TGrou---c60886e1\src\System.Reflection.Primitives\src\System.Reflection.Primitives.csproj]

**Comment by luqunl** [comment]
The following testcase failed..
System.Diagnostics.PerformanceCounter.Tests
System.Reflection.Metadata.Tests
