### ISSUE TITLE
'GroupCollection' does not contain a definition for 'Count'

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/corefx#41445]
I recently tried to move my web application from .net cor 2.2 to 3.0. While the following code used to compile and run just fine, it now gives the error at every occurrence where Count is invoked on a System.Text.RegularExpressions.Match object

internal virtual bool IsValidKeywordFormat(Match m, out string error)
        {

            int matches = m.Groups.Count(t => t.Success);
            ......

Error: CS1061 : 'GroupCollection' does not contain a definition for 'Count' and no accessible extension method 'Count' accepting a first argument of type 'GroupCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by mayur-ekbote** [comment]
Sure. Using Match.Value also fixes this problem. But I was wondering why it worked in 2.2 and stopped working in 3.0. It was a breaking change,

**Comment by kavun** [comment]
```c#
int matches = m.Groups.Values.Count(t => t.Success);
```

This might be more readable. I'm also confused by this seemingly breaking change.

**Comment by scalablecory** [comment]
@mayur-ekbote @kavun can you supply a self-contained sample that compiles in 2.2 but fails to compile with 3.0?

`GroupCollection.Count` does exist, but it is an integer property, not a method. The only other `Count` I'm aware of is an extension method on `IEnumerable<T>`, which `GroupCollection` does not implement.

**Comment by danmosemsft** [comment]
I am guessing it relates to this https://github.com/dotnet/corefx/pull/30077 which made this change:
```c#
<<<    public partial class GroupCollection : System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.Generic.ICollection<System.Text.RegularExpressions.Group>, System.Collections.Generic.IEnumerable<System.Text.RegularExpressions.Group>, System.Collections.Generic.IList<System.Text.RegularExpressions.Group>, System.Collections.Generic.IReadOnlyCollection<System.Text.RegularExpressions.Group>, System.Collections.Generic.IReadOnlyList<System.Text.RegularExpressions.Group>, System.Collections.IList
>>>    public partial class GroupCollection : System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.Generic.ICollection<System.Text.RegularExpressions.Group>, System.Collections.Generic.IEnumerable<System.Text.RegularExpressions.Group>, System.Collections.Generic.IList<System.Text.RegularExpressions.Group>, System.Collections.Generic.IReadOnlyCollection<System.Text.RegularExpressions.Group>, System.Collections.Generic.IReadOnlyList<System.Text.RegularExpressions.Group>, System.Collections.IList, System.Collections.Generic.IReadOnlyDictionary<string, Group>
```
specifically it added `IReadOnlyDictionary<string, Group>`. @scalablecory can you see how that would cause this error?

**Comment by danmosemsft** [comment]
It already had 
```c#
        IEnumerator<Group> IEnumerable<Group>.GetEnumerator() => new Enumerator(this);
```
and this change added also
```c#
        IEnumerator<KeyValuePair<string, Group>> IEnumerable<KeyValuePair<string, Group>>.GetEnumerator()
```
Perhaps it doesn't know which to bind to.

**Comment by scalablecory** [comment]
@danmosemsft that looks correct. Not sure how we'd fix that short of reverting the change.

**Comment by danmosemsft** [comment]
@bartonjs @stephentoub thoughts about this kind of breaking change? I feel like we've talked about this before and treated them on case by case bases.

**Comment by bartonjs** [comment]
If it was caught in preview we probably would have reverted it; but given that we've already shipped an LTS version with the change it's probably there forever now.

Somewhat ironically, we were talking about an overload ambiguity problem from IEnumerable and IReadOnlyDictonary in an API Review today, but we apparently missed this as an ambiguity on extension method invocation because this now has two different IEnumerable\<T\>s.

I'm not sure there's a good solution here.  We'd have to make instance methods on the collection type, or exact-match versions of all IEnumerable\<T\>-accepting extension methods.

**Comment by bartonjs** [comment]
Specifying the generic should work at the call-site:

```C#
int matches = m.Groups.Values.Count<Group>(t => t.Success);
```

It's only generic inference that fails due to the ambiguity.

**Comment by danmosemsft** [comment]
Is this a check we could build into one of our compatibility checker tools, eg., apicompat? 

Although, I guess all changes that could potentially cause this would be additive changes visible in an API review at some point, so the scrutiny should be possible there rather than on every PR.

**Comment by bartonjs** [comment]
The problem is when you gain a second (specifically second) implementation of an interface, IEnumerable\<T\> being both the most common and the one with the most extension methods.

Probably what happened was "hey, why doesn't GroupCollection implement IReadOnlyDictionary? it seems like it functions as one, but can't be used in IReadOnlyDictionary extension methods...", that led to an API proposal, and during API review we neglected to notice that the type was now both `IEnumerable<Group>` and `IEnumerable<KeyValuePair<string, Group>>`, because that's implicit via `IReadOnlyDictionary<string,Group>`.

If you already have two, the extension methods are already cut off, so a 3rd isn't a problem.

It looks like APIGen would have highlighted this a bit better, since it flattens out all interface declarations, but the ref.cs change in the PR was done by hand.  The current ref.cs shows multiple IEnumerable\<T\> implementations:

```C#
public partial class GroupCollection :
    System.Collections.Generic.ICollection<System.Text.RegularExpressions.Group>,
    System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, System.Text.RegularExpressions.Group>>,
    System.Collections.Generic.IEnumerable<System.Text.RegularExpressions.Group>,
    System.Collections.Generic.IList<System.Text.RegularExpressions.Group>,
    System.Collections.Generic.IReadOnlyCollection<System.Collections.Generic.KeyValuePair<string, System.Text.RegularExpressions.Group>>,
    System.Collections.Generic.IReadOnlyCollection<System.Text.RegularExpressions.Group>,
    System.Collections.Generic.IReadOnlyDictionary<string, System.Text.RegularExpressions.Group>,
    System.Collections.Generic.IReadOnlyList<System.Text.RegularExpressions.Group>,
    System.Collections.ICollection,
    System.Collections.IEnumerable,
    System.Collections.IList
{
    ...
}
```

If we wanted to have tooling we'd do something like make a tool fail the build if a public type implements the same interface twice with different generic type arguments; but we'd have to give it a grandfathered list of broken types.  Otherwise, it's the collective brain power of API Review and preview usage.

**Comment by danmosemsft** [comment]
OK. Too bad. @mayur-ekbote thanks for reporting it. Hopefully you can use one of these workarounds above.

@PriyaPurkayastha where do we add a breaking change note? This is from 2.2 to 3.0

**Comment by PriyaPurkayastha** [comment]
Same breaking change template https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md can be used. Version introduced section will have .NET Core 3.0 and description will state that this is a change in behavior from 2.2. 
cc @gewarren for awareness that this will come up for documentation.

**Comment by danmosemsft** [comment]
@scalablecory mind adding a quick note for this one ?
