### PR TITLE
Enable native build with Clang 6.0

### PR DESCRIPTION
**Pull request by kasper3**
Three kinds of warnings were reported as errors with Clang 6.0:

```
[ 35%] Building C object System.Native/CMakeFiles/System.Native-Static.dir/pal_networking.c.o
/corefx/src/Native/Unix/System.Native/pal_networking.c:2048:19: error: implicit conversion changes signedness:
      'enum SocketEvents' to 'int32_t' (aka 'int') [-Werror,-Wsign-conversion]
    sae->Events = GetSocketEvents(events);
                ~ ^~~~~~~~~~~~~~~~~~~~~~~
```

```
[ 37%] Building CXX object System.Native/CMakeFiles/System.Native.dir/pal_process.cpp.o
/corefx/src/Native/Unix/System.Native/pal_process.cpp:370:38: error: result of comparison 'uint64_t'
      (aka 'unsigned long') > 18446744073709551615 is always false [-Werror,-Wtautological-type-limit-compare]
    if (value == UINT64_MAX || value > std::numeric_limits<rlim_t>::max())
                               ~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
[ 68%] Building CXX object System.Net.Http.Native/CMakeFiles/System.Net.Http.Native-Static.dir/pal_easy.cpp.o
/corefx/src/Native/Unix/System.Net.Http.Native/pal_easy.cpp:11:38: error: comparison of two values with different
      enumeration types ('PAL_CURLoption' and 'CURLoption') [-Werror,-Wenum-compare]
static_assert(PAL_CURLOPT_INFILESIZE == CURLOPT_INFILESIZE, "");
              ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~

(and lots of these)
```

With this fix, CoreFX builds with Clang 6.0. Tested on Ubuntu 18.04.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @janvorli

File: src/Native/Unix/System.Native/pal_process.cpp [hunk 1]
```diff
@@ -367,7 +367,11 @@ static int32_t ConvertRLimitResourcesPalToPlatform(RLimitResources value)
 static rlim_t ConvertFromManagedRLimitInfinityToPalIfNecessary(uint64_t value)
 {
     // rlim_t type can vary per platform, so we also treat anything outside its range as infinite.
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wunknown-pragmas"
```
Comment (janvorli) [inline src/Native/Unix/System.Native/pal_process.cpp]: I am not sure I understand the reason for ignoring the -Wunknown-pragmas here.

File: src/Native/Unix/CMakeLists.txt [hunk 2]
```diff
@@ -19,6 +19,7 @@ add_compile_options(-Wno-old-style-cast)
 add_compile_options(-Wno-cast-align)
 add_compile_options(-Wno-typedef-redefinition)
 add_compile_options(-Wno-unused-local-typedef)
+add_compile_options(-Wno-enum-compare)
```
Comment (janvorli) [inline src/Native/Unix/CMakeLists.txt]: I would prefer fixing the compares by casting the enum values to ints before comparison instead. I consider disabling the warning globally to be the last resort.

File: src/Native/Unix/System.Native/pal_process.cpp (hunk 1 above)
Comment (kasper3) [reply src/Native/Unix/System.Native/pal_process.cpp]: `-Wunknown-pragmas` is for older Clang which don't have `-Wtautological-type-limit-compare`. It was failing on macOS and CentOS (Clang 3.9)

File: src/Native/Unix/CMakeLists.txt (hunk 2 above)
Comment (kasper3) [reply src/Native/Unix/CMakeLists.txt]: IMO, those asserts are for sanity check. It was this one liner or casting those enum lines in multiple files. It's not a very useful warning, in fact less useful than `-Wno-cast-align` which we are ignoring on line 19. But I don't have strong opinion.

Comment (janvorli) [reply src/Native/Unix/CMakeLists.txt]: But this disables the warnings for all the files. So if someone makes a mistake elsewhere and compares really unrelated enums, it would go unnoticed.

File: src/Native/Unix/System.Native/pal_process.cpp (hunk 1 above)
Comment (janvorli) [reply src/Native/Unix/System.Native/pal_process.cpp]: Interesting, ok. I would expect that unknown pragma would warn against using a completely unknown pragma and not just a known pragma with unknown parameter.

**Comment by pjanotti** [comment]
FYI: iIt seems that this does not work with the latest clang installed by Xcode. I guess I will have to get clang via brew and somehow access the version that we support... 

```
pal_process.cpp:372:34: error: unknown warning group '-Wtautological-type-limit-compare', ignored [-Werror,-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wtautological-type-limit-compare"

clang version:

Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by janvorli** [comment]
@kasper3 it looks like we'll also need to add disabling the `-Wunknown-warning-option` option to the pragmas you've added in your change. Could you please fix that?

**Comment by kasper3** [comment]
@pjanotti, this is strange soup of warnings. I added `#pragma clang diagnostic ignored "-Wunknown-pragmas"` to satisfy macos clang's version used by CI: https://github.com/kasper3/corefx/blob/a94d7fee8a835565e0747d9fd216b994d8b97120/src/Native/Unix/System.Native/pal_process.cpp#L371, can you please add ,#pragma clang diagnostic ignored "-Wunknown-warning-option" on the next line.

**Comment by kasper3** [comment]
@janvorli, sure. Once we get the confirmation from @pjanotti that it fixes the build with XCode 9.3, I will issue a PR. (I don't have Mac handy atm)

**Comment by pjanotti** [comment]
@kasper3 that fixed it for me.
