### PR TITLE
Add shims for libcurl multi_* functions.

### PR DESCRIPTION
**Pull request by eerhardt**
Adding shims for all of the libcurl multi_* functions. I was able to remove all of the structs being used.

There is only 1 place left to shim for libcurl, and it is a little tricky. Libcurl has some callback functions that use 'size_t' and 'long' in their signatures. To shim this, I will need to add some native 'thunk' functions that will do the marshalling between size_t and long to the managed stable signature. This will be my next task.

@bartonjs @stephentoub @nguerrera @sokket @vijaykota @kapilash @shrutigarg

### CODE REVIEW

File: src/Native/System.Net.Http.Native/pal_multi.cpp [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+{
+    return curl_multi_add_handle(multi_handle, easy_handle);
+}
+
+extern "C" int32_t MultiRemoveHandle(CURLM* multi_handle, CURL* easy_handle)
+{
+    return curl_multi_remove_handle(multi_handle, easy_handle);
+}
+
+extern "C" int32_t MultiWait(CURLM* multi_handle, int32_t extraFileDescriptor, int32_t* isExtraFileDescriptorActive, int32_t* isTimeout)
```
Comment (nguerrera) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: nit: replace _ with camelCase

File: src/System.Net.Http/src/System.Net.Http.csproj [hunk 2]
```diff
@@ -221,21 +218,11 @@
...
-    <Compile Include="$(CommonPath)\Interop\FreeBSD\Interop.Libraries.cs">
-      <Link>Common\Interop\FreeBSD\Interop.Libraries.cs</Link>
-    </Compile>
-  </ItemGroup>
   <ItemGroup Condition="'$(TargetsOSX)' == 'true'">
     <Compile Include="$(CommonPath)\Interop\OSX\Interop.Libraries.cs">
       <Link>Common\Interop\OSX\Interop.Libraries.cs</Link>
     </Compile>
   </ItemGroup>
-  <ItemGroup Condition="'$(TargetsLinux)' == 'true'">
```
Comment (nguerrera) [inline src/System.Net.Http/src/System.Net.Http.csproj]: Is the TargetsOSX group still needed?

File: src/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj [hunk 3]
```diff
@@ -283,21 +283,11 @@
...
-    <Compile Include="$(CommonPath)\Interop\FreeBSD\Interop.Libraries.cs">
-      <Link>Common\Interop\FreeBSD\Interop.Libraries.cs</Link>
-    </Compile>
-  </ItemGroup>
   <ItemGroup Condition="'$(TargetsOSX)' == 'true'">
     <Compile Include="$(CommonPath)\Interop\OSX\Interop.Libraries.cs">
       <Link>Common\Interop\OSX\Interop.Libraries.cs</Link>
     </Compile>
   </ItemGroup>
-  <ItemGroup Condition="'$(TargetsLinux)' == 'true'">
```
Comment (nguerrera) [inline src/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj]: Same question: OSX group still needed?

File: src/Native/System.Net.Http.Native/pal_multi.cpp [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+{
+    if (!isExtraFileDescriptorActive || !isTimeout)
+    {
+        if (isExtraFileDescriptorActive)
```
Comment (sokket) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: != nullptr (and below)

File: src/Native/System.Net.Http.Native/pal_multi.cpp [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    // just in case something goes wrong we can recover gracefully.  This timeout is relatively long.
+    // Note, though, that libcurl has its own internal timeout, which can be requested separately
+    // via curl_multi_timeout, but which is used implicitly by curl_multi_wait if it's shorter
+    // than the value we provide.
+    const int FailsafeTimeoutMilliseconds = 1000;
+
+    int numFds;
+    CURLMcode result = curl_multi_wait(multi_handle, &extraFds, 1, FailsafeTimeoutMilliseconds, &numFds);
+
+    *isExtraFileDescriptorActive = (extraFds.revents & CURL_WAIT_POLLIN) != 0;
```
Comment (sokket) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: Add an assert check so we don't AV

File: src/Native/System.Net.Http.Native/pal_multi.cpp [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+
+extern "C" int32_t MultiPerform(CURLM* multi_handle)
+{
+    int running_handles;
+    return curl_multi_perform(multi_handle, &running_handles);
+}
+
+static int32_t DefaultMessageInfo(int32_t* message, CURL** easy_handle, int32_t* result)
+{
+    if (message)
```
Comment (sokket) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: Please use ```!= nullptr``` when checking pointers

Comment (sokket) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: And below (I'll stop commenting on this)

File: src/Native/System.Net.Http.Native/pal_multi.h [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+extern "C" int32_t MultiPerform(CURLM* multi_handle);
+
+/*
+Ask the multi handle if there are any messages/informationals from the individual transfers.
+Shims the curl_multi_info_read function.
+
+Returns 1 if a CURLMsg was retrieved and the out variables are set, 
+otherwise 0 when there are no more messages to retrieve.
+*/
+extern "C" int32_t MultiInfoRead(CURLM* multi_handle, int32_t* message, CURL** easy_handle, int32_t* result);
```
Comment (kapilash) [inline src/Native/System.Net.Http.Native/pal_multi.h]: Nit: "result" does not seem very appropriate name for third parameter; it represents pending requests.

Incidentally, we do not use the value of that. Perhaps we can skip it. Like wise on the message. At this point the value of message is always CURL_MSGDONE.

We only care about the easyHandle. 
Perhaps we can simplify the signature and return only the useful/relevant data?

File: src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+        public static extern CURLMcode MultiPerform(SafeCurlMultiHandle multi_handle);
+
+        [DllImport(Libraries.HttpNative)]
+        [return: MarshalAs(UnmanagedType.Bool)]
+        public static extern bool MultiInfoRead(SafeCurlMultiHandle multi_handle, out CURLMSG message, out IntPtr easy_handle, out CURLcode result);
+
+        [DllImport(Libraries.HttpNative)]
+        public static extern IntPtr MultiGetErrorString(int code);
+
+        // Class for constants defined for the enum CURLMcode in multi.h
```
Comment (kapilash) [inline src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs]: Nit: CURLMcode and CURLMsg aren't classes anymore.

**Comment by vijaykota** [comment]
Same comment as @nguerrera about OSX target in .csproj. LGTM otherwise

File: src/Common/src/Interop/Unix/libcurl/Interop.libcurl_types.cs [hunk 9]
```diff
@@ -32,38 +18,6 @@ internal static partial class CURL_SEEKFUNC
...
-        {
-            internal int fd;
-            internal short events;
-            internal short revents;
-        };
-#pragma warning restore 0649
-
         public delegate size_t curl_readwrite_callback(
             IntPtr buffer,
             size_t size,
```
Comment (stephentoub) [inline src/Common/src/Interop/Unix/libcurl/Interop.libcurl_types.cs]: We shouldn't be using size_t in our interop.  But I guess this will be shim'd separately?

File: src/Native/System.Net.Http.Native/pal_multi.cpp [hunk 10]
```diff
@@ -0,0 +1,114 @@
...
+}
+
+extern "C" int32_t MultiRemoveHandle(CURLM* multi_handle, CURL* easy_handle)
+{
+    return curl_multi_remove_handle(multi_handle, easy_handle);
+}
+
+extern "C" int32_t MultiWait(CURLM* multi_handle, int32_t extraFileDescriptor, int32_t* isExtraFileDescriptorActive, int32_t* isTimeout)
+{
+    if (!isExtraFileDescriptorActive || !isTimeout)
```
Comment (stephentoub) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: Fine for now, but I think we should make a pass through our shims and replace this kind of argument checking with asserts.  These are really meant to be internal implementation details, as if one managed function was calling another in the same assembly, and in general we don't need to code defensively against other callers.

File: src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs [hunk 11]
```diff
@@ -0,0 +1,79 @@
...
+
+        [DllImport(Libraries.HttpNative)]
+        public static extern CURLMcode MultiRemoveHandle(SafeCurlMultiHandle multi_handle, SafeCurlHandle easy_handle);
+
+        [DllImport(Libraries.HttpNative)]
+        public static extern CURLMcode MultiWait(
+            SafeCurlMultiHandle multi_handle,
+            int extraFileDescriptor,
+            [MarshalAs(UnmanagedType.Bool)] out bool isExtraFileDescriptorActive,
+            [MarshalAs(UnmanagedType.Bool)] out bool isTimeout);
```
Comment (stephentoub) [inline src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs]: Also fine for now, but I think we should go through our shims and remove all adornments like this which are just restating the default.

**Comment by stephentoub** [comment]
LGTM

File: src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs (hunk 11 above)
Comment (eerhardt) [inline src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs]: I will remove them here.

File: src/Native/System.Net.Http.Native/pal_multi.cpp (hunk 1 above)
Comment (eerhardt) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: Fixed.

File: src/System.Net.Http/src/System.Net.Http.csproj (hunk 2 above)
Comment (eerhardt) [inline src/System.Net.Http/src/System.Net.Http.csproj]: Looks like it can be removed.

File: src/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj (hunk 3 above)
Comment (eerhardt) [inline src/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj]: Looks like it can be removed.

File: src/Native/System.Net.Http.Native/pal_multi.cpp (hunk 5 above)
Comment (eerhardt) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: What should I be asserting?

The check for isExtraFileDescriptorActive is at the beginning of the method.

File: src/Native/System.Net.Http.Native/pal_multi.cpp (hunk 4 above)
Comment (eerhardt) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: For my understanding - what is the benefit/difference here? Is it readability?

File: src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs (hunk 8 above)
Comment (eerhardt) [inline src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Multi.cs]: Fixed.

File: src/Common/src/Interop/Unix/libcurl/Interop.libcurl_types.cs (hunk 9 above)
Comment (eerhardt) [inline src/Common/src/Interop/Unix/libcurl/Interop.libcurl_types.cs]: Yes, these 2 callbacks are a little tricky and I wanted to do them by themselves. So they are not yet implemented.

File: src/Native/System.Net.Http.Native/pal_multi.cpp (hunk 10 above)
Comment (eerhardt) [inline src/Native/System.Net.Http.Native/pal_multi.cpp]: I'll change these to asserts, so someone doesn't need to 'fix them up' later.

**Comment by eerhardt** [comment]
I've responded to feedback and pushed a new commit.

**Comment by chcosta** [comment]
I've just started this failure in CoreFx builds on CentOS 7.1.1503

2015-11-02T18:00:27.683Z: [ 12%] Building C object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/openssl.c.o
2015-11-02T18:00:27.772Z:  error: use of undeclared identifier 'CURLM_ADDED_ALREADY'; did you mean 'PAL_CURLM_ADDED_ALREADY'?
2015-11-02T18:00:27.772Z: static_assert(PAL_CURLM_ADDED_ALREADY == CURLM_ADDED_ALREADY, "");
2015-11-02T18:00:27.773Z:                                          ^~~~~~~~~~~~~~~~~~~
2015-11-02T18:00:27.773Z:                                          PAL_CURLM_ADDED_ALREADY
2015-11-02T18:00:27.773Z: /root/corefx/src/Native/System.Net.Http.Native/pal_multi.h:19:5: note: 'PAL_CURLM_ADDED_ALREADY' declared here
2015-11-02T18:00:27.773Z:     PAL_CURLM_ADDED_ALREADY = 7,
2015-11-02T18:00:27.773Z:     ^
2015-11-02T18:00:27.780Z: 1 error generated.
2015-11-02T18:00:27.782Z: make[2]: *** [System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/pal_multi.cpp.o] Error 1

**Comment by eerhardt** [comment]
2 quick questions:
1. Do we have CentOS running in our CI?
2. What version of libcurl is installed on your CentOS?

**Comment by eerhardt** [comment]
It looks like this error code was added in version 7.32.1.
https://github.com/bagder/curl/blob/cba5bc58541005bcacf65b31ebfe9b6f7484899b/docs/libcurl/symbols-in-versions#L298

**Comment by eerhardt** [comment]
@chcosta - Can you log an issue for this? I can fix it.

**Comment by chcosta** [comment]
Yes, we have CentOs in our CI (internal VSO CI) and it is running libcurl 7.29.0.  I'll file an issue.
