### PR TITLE
WinHttpHandler ResponseStream reads should return back with partial data

### LINKED ISSUE #1825: HttpClient ReadAsync waits for whole buffer to fill up even if HttpCompletionOption.ResponseHeadersRead is set
Hi,

I've prepared a simple project to demonstrate my issue:
https://github.com/ppekrol/ReadAsyncIssue

Steps to reproduce:
1. Run web (ReadAsyncIssue), can be under DNX451 or DNXCORE50, no difference
2. Run console app:
a) when DNX451 is used, ReadAsync returns immediately (read length = 100)
b) when DNXCORE50 is used, ReadAsync waits for buffer to fill (8192)

I think this is a bug.

### PR DESCRIPTION
**Pull request by davidsh**
.NET Stream.Read() semantics leave it to the implementation to decide how much data to return given a buffer of size N:

https://msdn.microsoft.com/en-us/library/system.io.stream.read(v=vs.110).aspx
"An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached."

The behavior of System.Net HTTP APIs (i.e. .NET Framework) are such that stream reads are able to return as soon as data is available. They don't wait until the provided buffer is full. The current WinHttpHandler was not behaving that way because it didn't call WinHttpQueryDataAvailable before calling WinHttpReadData. WinHttpQueryDataAvailable would indicate how many bytes can be read immediately.

This fix changes the WinHttpResponseStream.Read* methods to use WinHttpQueryDataAvailable before calling WinHttpReadData.

Added both WinHttpHandler unit tests (helps with simulating/testing network errors) and HttpClientHandler functional tests (which will test x-plat).

Fixes #1825

### CODE REVIEW

**Comment by davidsh** [comment]
@stephentoub @CIPop PTAL

File: src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestCallback.cs [hunk 1]
```diff
@@ -127,6 +133,15 @@ private static void OnRequestSendRequestComplete(WinHttpRequestState state)
             state.TcsSendRequest.TrySetResult(true);
         }
 
+        private static void OnRequestDataAvailable(WinHttpRequestState state, int bytesAvailable)
+        {
+            Debug.Assert(state != null, "OnRequestDataAvailable: state is null");
```
Comment (stephentoub) [inline src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestCallback.cs]: Consider adding an assert that bytesAvailable is > 0.  If it's possible instead that it is 0, I assume we don't want to be completing the data available task.

File: src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs [hunk 2]
```diff
@@ -131,21 +131,57 @@ public override Task<int> ReadAsync(byte[] buffer, int offset, int count, Cancel
...
+                                Marshal.UnsafeAddrOfPinnedArrayElement(buffer, offset),
+                                (uint)bytesToRead,
+                                IntPtr.Zero))
+                            {
+                                _state.TcsReadFromResponseStream.TrySetException(
+                                    new IOException(SR.net_http_io_read, WinHttpException.CreateExceptionUsingLastError()));
+                            }
+                        }
+                    }
+                });
```
Comment (stephentoub) [inline src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs]: This should include:
```C#
), CancellationToken.None, TaskContinuationOptions.None, TaskScheduler.Default);
```
the important piece being the TaskScheduler.Default.  Later you could decide to also pass in a value for the object state arg, which would potentially let you eliminate the closure and delegate allocations per call.

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs [hunk 3]
```diff
@@ -374,6 +374,27 @@ public void MaxRequestContentBufferSize_Set_ThrowsPlatformNotSupportedException(
             }
         }
 
+        [Fact]
+        public async Task SendAsync_ReadFromSlowStreamingServer_PartialDataReturned()
+        {
+            // TODO: This is a placeholder until GitHub Issue #2383 gets resolved.
+            const string SlowStreamingServer = "http://httpbin.org/drip?numbytes=8192&duration=15&delay=1&code=200";
```
Comment (stephentoub) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: How slow is this?   Should it be [OuterLoop]?

**Comment by stephentoub** [comment]
A few minor nits (and a compilation error), but generally LGTM

File: src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs (hunk 2 above)
Comment (davidsh) [inline src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs]: I'll add this:

`), CancellationToken.None, TaskContinuationOptions.None, TaskScheduler.Default);`

In terms of passing in the `state` arg, there are also the `buffer`, `offset`, etc. parameters from the outer scope to pass in as well.  Not sure yet how I'll optimize that bundle of info to avoid the closure. Might do that part in another PR.

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs (hunk 3 above)
Comment (davidsh) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: It's not really slow. At most, if the test fails, it would take 15 seconds to drip the 8192 bytes. But when the test passes, the ReadAsync() call will return much faster with partial data.

**Comment by davidsh** [comment]
The compilation error was due to a missing file change caused when I tried to fix my branch based on a bad merge.

File: src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestCallback.cs (hunk 1 above)
Comment (davidsh) [inline src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestCallback.cs]: it could return 0.  That means 'end-of-file' and so, we do want to complete the task and then do the real `WinHttpReadData` call.

More info from the docs:

>This function returns the number of bytes of data that are available to read immediately by a subsequent call to WinHttpReadData. If no data is available and the end of the file has not been reached, then, the function returns TRUE, and when data becomes available, calls the callback function with WINHTTP_STATUS_CALLBACK_DATA_AVAILABLE and indicates the number of bytes immediately available to read by calling WinHttpReadData.

**Comment by davidsh** [comment]
CI Failed on Linux:
Build: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/6065/

test failed on Linux:
System.Net.Http.Functional.Tests.HttpClientHandlerTest.SendAsync_ReadFromSlowStreamingServer_PartialDataReturned
"bytesRead should be less than buffer.Length Expected: True Actual: False"

Will open new issue

**Comment by stephentoub** [comment]
> Will open new issue

Hmm, I don't actually think that test is valid.  Just as there's no requirement that Stream.Read return as much as was asked for, there's no guarantee it won't (unless of course the stream ends before that much data is available).  Whether the implementation chooses to give back what it has or not is an implementation detail.  And even if WinHttpHandler does choose to give back partial data immediately, I expect this test will still fail from time to time on Windows, given that it's based on a race condition; if something in the network were to cause all of the data to arrive together, or the test system got slowed a bit and ended up noticing all of the data at the same time, etc., the test would fail.

**Comment by stephentoub** [comment]
(That said, I'll see if there's something that can be done to get libcurl to call back more frequently.  I believe our code is correct in terms of passing any data as soon as it's given to us, so it seems like it would just be a matter of configuring libcurl to call us back more promptly in cases like this.)

**Comment by stephentoub** [comment]
I just took a look, and I can't get it to fail locally.  That implies to me it is just hitting the aforementioned race condition.  libcurl has an internal buffer.  If it has any data in that buffer and it's unable to read any more data off the wire at the moment, then it'll call back to CurlHandler immediately with that data.  If, however, it is able to read more data, then it'll read as much as it can as long as the buffer isn't yet full and there's more data to be read.  This minimizes the number of callbacks while also not starving the callback.  We could lower the size of that internal buffer if we wanted (CURLOPT_BUFFERSIZE), forcing it to call back more frequently even if there's data that can be read off the wire, but I'm not sure we want to do that, or whether we could choose a value better than libcurl's default.  @kapilash, thoughts?

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs (hunk 3 above)
Comment (stephentoub) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: FWIW, it currently takes ~20 seconds for me, when passing, on both Windows and Linux.

**Comment by kapilash** [comment]
> This minimizes the number of callbacks while also not starving the callback. We could lower the size of that internal buffer if we wanted (CURLOPT_BUFFERSIZE), forcing it to call back more frequently even if there's data that can be read off the wire, but I'm not sure we want to do that, or whether we could choose a value better than libcurl's default.

 I thought, when there are more than one active requests , higher the value of  buffer size, better  over all through put (assuming eager consumers for each of the requests - that is no "pause requests").

FWIW, I copied the code of ```SendAsync_ReadFromSlowStreamingServer_PartialDataReturned``` from this PR in a program and ran it multiple times. First set of runs with default value of buffer size and second set with CURLOPT_BUFFERSIZE set to 1024.
In the first set of runs (default value of buffer_size), I saw a failure about once in five times. (4 failures out of 20 runs).
In the second set of runs, I did not see any failure in 20 runs. 
But, as of now,  I do not know the ideal value of CURLOPT_BUFFERSIZE or how to calculate it. I can study this further and get back to you :)

**Comment by CIPop** [comment]
LGTM

File: src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs (hunk 3 above)
Comment (stephentoub) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: @davidsh, are you not seeing this taking so long on your machine?

Comment (davidsh) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: @stephentoub Running all the System.Net.Http/tests/FunctionalTests takes 41 seconds on my dev box.

Are you saying it takes 20 seconds just for that single test?

Comment (stephentoub) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: > Are you saying it takes 20 seconds just for that single test?

Yes.

Comment (davidsh) [inline src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs]: @stephentoub Ok. I ran this single test several times and it did average around 20 seconds on my dev box.

We're currently the httpbin.org server for this "slow streaming" test.  It might have behaviors we don't understand. It is supposed to "drip" the 8192 bytes over 15 seconds at most. 

This is one of the difficulties of getting networking tests of this nature as functional tests over the real internet. For the WinHttpHandler fix itself, I wrote unit tests so that we can mock the network and get exact behaviors we want in order to test the desired codepaths.

I wanted to have a functional test in HttpClientHandler to validate that CurlHandler is behaving correctly.  This particular test is not very different from an actual customer scenario for which this bug was fixed.

If we think this current test is too brittle or unreliable, then I can remove it. But we still need a way of validating CurlHandler for this streaming scenario.
