### ISSUE TITLE
Multiple assemblies with equivalent identity have been imported

### ISSUE THREAD

**Issue by CalvinFengDatacom** [dotnet/corefx#37103]
Hi Guys,

I have a wired issue with my .Net project after I push my changes to remote repository in DevOps.

The situation is, we have a .Net project was in .Net framework in version 4.6, then because of other dependencies, we need to upgrade the .Net framework to 4.6.2. It built successfully locally, but it built failed in the build pipeline of DevOps.

The error message is: 

- CSC(0,0): Error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\a\1\s\DNZ.Mocabots.AIA\packages\System.Runtime.Serialization.Primitives.4.1.1\lib\net46\System.Runtime.Serialization.Primitives.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Runtime.Serialization.Primitives.dll'. Remove one of the duplicate references.
- CSC(0,0): Error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\a\1\s\DNZ.Mocabots.AIA\packages\System.Runtime.InteropServices.4.1.0\lib\net462\System.Runtime.InteropServices.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Runtime.InteropServices.dll'. Remove one of the duplicate references.
- CSC(0,0): Error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\a\1\s\DNZ.Mocabots.AIA\packages\System.Runtime.Extensions.4.1.0\lib\net462\System.Runtime.Extensions.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Runtime.Extensions.dll'. Remove one of the duplicate references.
- CSC(0,0): Error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\a\1\s\DNZ.Mocabots.AIA\packages\System.Runtime.4.1.0\lib\net462\System.Runtime.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Runtime.dll'. Remove one of the duplicate references.
- CSC(0,0): Error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\a\1\s\DNZ.Mocabots.AIA\packages\System.IO.4.1.0\lib\net462\System.IO.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.IO.dll'. Remove one of the duplicate references.
- Process 'msbuild.exe' exited with code '1'.

I can see there are lots of suggestions of removing one of the conflict file manually, however it doesn't work for me. 

_**Note again, we are using .Net Standard F/W, not .Net Core.**
It was in 4.6 and now it's in 4.6.2._

Looking forward from your ideas, thanks
