### PR TITLE
Fixed suppressed XML documentation errors

### PR DESCRIPTION
**Pull request by StanislavUshakov**
Part of #33934

### CODE REVIEW

File: src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj [hunk 1]
```diff
@@ -6,7 +6,6 @@
     <AssemblyName>System.Diagnostics.Process</AssemblyName>
     <DefineConstants Condition="'$(TargetGroup)' != 'uap'">$(DefineConstants);FEATURE_REGISTRY</DefineConstants>
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
-    <NoWarn>$(NoWarn);CS0419;CS1572;CS1573;CS1587;CS1591</NoWarn>
```
Comment (sharwell) [inline src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj]: 📝 I generally recommend leaving three warnings disabled across a project:

* CS1573: Parameter 'parameter' has no matching param tag in the XML comment for 'parameter' (but other parameters do)
* CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'
* CS1712: Type parameter 'type_parameter' has no matching typeparam tag in the XML comment on 'type_or_member' (but other type parameters do)

File: src/System.ComponentModel.Composition/src/Microsoft/Internal/GenerationServices.cs [hunk 2]
```diff
@@ -225,9 +223,8 @@ public static void AddLocalToLocalDictionary(this ILGenerator ilGenerator, Local
 
         /// Generates the code to get the type of an object and store it in a local
         /// <param name="ilGenerator"></param>
-        /// <param name="dictionary"></param>
-        /// <param name="key"></param>
-        /// <param name="value"></param>
+        /// <param name="exception"></param>
+        /// <param name="dataStore"></param>
```
Comment (sharwell) [inline src/System.ComponentModel.Composition/src/Microsoft/Internal/GenerationServices.cs]: 📝 This is why I leave 1573 disabled. This is a duplication of content two lines below.

File: src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs [hunk 3]
```diff
@@ -116,7 +116,7 @@ private void WriteAssert(string stackTrace, string message, string detailMessage
 
         /// <devdoc>
         ///    <para>
-        ///       Writes the output using <see cref="System.Diagnostics.Debug.Write"/>.
+        ///       Writes the output using <see cref="M:System.Diagnostics.Debug.Write(string)"/>.
```
Comment (sharwell) [inline src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs]: ❗️ You can't mix C# keywords with fully-expanded type names. This reference needs to be updated to do either of the following:

1. Remove `M:`
2. Change `string` &rarr; `System.String`

File: src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs [hunk 4]
```diff
@@ -126,7 +126,7 @@ public override void Write(string message)
 
         /// <devdoc>
         ///    <para>
-        ///       Writes the output followed by a line terminator using <see cref="System.Diagnostics.Debug.Write"/>.
+        ///       Writes the output followed by a line terminator using <see cref="M:System.Diagnostics.Debug.Write(string)"/>.
```
Comment (sharwell) [inline src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs]: ❗️ Also incorrect; same as previous

File: src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj (hunk 1 above)
Comment (StanislavUshakov) [reply src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj]: Thanks for the quick review.
As I understand we have CS1573 and CS1591 globally disabled via [Directory.Build.props](https://github.com/dotnet/corefx/blob/master/Directory.Build.props#L482)

File: src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs (hunk 3 above)
Comment (StanislavUshakov) [reply src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs]: Indeed, thank you. I will remove M to stay consistent.

File: src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs (hunk 4 above)
Comment (StanislavUshakov) [reply src/System.Diagnostics.TraceSource/src/System/Diagnostics/DefaultTraceListener.cs]: Indeed, thank you. I will remove M to stay consistent (as it wasn't tehre before).

File: src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj (hunk 1 above)
Comment (sharwell) [reply src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj]: Thanks!

File: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs [hunk 5]
```diff
@@ -2535,7 +2535,7 @@ public static void RemoveProviderTransparent(TypeDescriptionProvider provider, T
         /// associated with.
         /// 
         /// This method can be called from partially trusted code. If 
-        /// <see cref="TypeDescriptorPermissionFlags.RestrictedRegistrationAccess"/>
+        /// <see cref="E:System.Security.Permissions.TypeDescriptorPermissionFlags.RestrictedRegistrationAccess"/>
```
Comment (sharwell) [inline src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs]: 📝 I previously assumed that `E:` was added here because this assembly doesn't reference an assembly defining the `TypeDescriptorPermissionFlags.RestrictedRegistrationAccess` member. If this is not correct, the preferable form for this reference and the one above it would be removing the `E:` prefix, since the inclusion of a prefix causes the compiler to not validate the reference at all.

Comment (StanislavUshakov) [reply src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs]: There is no reference so without the `E:` it throws an error even with the fully qualified name.

File: src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj (hunk 1 above)
Comment (stephentoub) [reply src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj]: > As I understand we have CS1573 and CS1591 globally disabled via Directory.Build.props

I would like to move away from that, though, with these disabled only for the projects that need it disabled.  We have projects that care a lot about XML comments as the primary source of documentation / IntelliSense / etc., and such warnings should be errors for those projects rather than being suppressed.

File: src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj [hunk 6]
```diff
@@ -7,7 +7,6 @@
     <ShouldWriteSigningRequired>false</ShouldWriteSigningRequired>
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
     <EnablePInvokeAnalyzer>false</EnablePInvokeAnalyzer>
-    <NoWarn>$(NoWarn);CS1572;CS1574;CS1587;CS1589;CS1591;CS1723;CS1734</NoWarn>
```
Comment (stephentoub) [inline src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj]:
```
System\PlatformDetection.Unix.cs(185,26): error CS1572: XML comment has a param tag for 'versionId', but there is no parameter by that name [D:\j\workspace\windows-TGrou---0d2c9ac4\src\CoreFx.Private.TestUtilities\src\CoreFx.Private.TestUtilities.csproj]
System\PlatformDetection.Unix.cs(196,26): error CS1572: XML comment has a param tag for 'versionId', but there is no parameter by that name [D:\j\workspace\windows-TGrou---0d2c9ac4\src\CoreFx.Private.TestUtilities\src\CoreFx.Private.TestUtilities.csproj]
```

Comment (StanislavUshakov) [reply src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj]: Thank you, I will check Linux and OSX builds separately because I was not able to build them locally,.

File: src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj (hunk 1 above)
Comment (StanislavUshakov) [reply src/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj]: Should we do it as a part of #33934 ?

File: src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj (hunk 6 above)
Comment (StanislavUshakov) [reply src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj]: I get strange error: `C:\corefx\external\runtime\runtime.depproj(94,5): error MSB3073: The command "chmod +x C:\corefx\artifacts\bin\testhost/netcoreapp-Linux-Debug-x64/dotnet" exited with code 9009.`
The command is: `build /p:os=OSX`

**Comment by StanislavUshakov** [comment]
Pushed another portion of projects updated.

File: src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj (hunk 6 above)
Comment (stephentoub) [reply src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj]: Try:
build /p:OSGroup=OSX
or
build /p:OSGroup=Linux

File: src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs [hunk 7]
```diff
@@ -182,7 +182,10 @@ private static bool IsRedHatFamilyAndVersion(int major = -1, int minor = -1, int
         /// Get whether the OS platform matches the given Linux distro and optional version.
         /// </summary>
         /// <param name="distroId">The distribution id.</param>
-        /// <param name="versionId">The distro version.  If omitted, compares the distro only.</param>
+        /// <param name="major">The distro major version.  If omitted, compares the distro only.</param>
+        /// <param name="minor">The distro minor version.  If omitted, compares the distro only.</param>
+        /// <param name="build">The distro build version.  If omitted, compares the distro only.</param>
+        /// <param name="revision">The distro revision version.  If omitted, compares the distro only.</param>
```
Comment (sharwell) [inline src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs]: 📝 These comments are not precise. It should say something like this:

> If omitted, this portion of the version is not included in the comparison.

The wording may vary, but the key is excluding a parameter impacts only that field and not the entire version number as the current comment suggests.

File: src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs [hunk 8]
```diff
@@ -193,7 +196,10 @@ private static bool IsDistroAndVersion(string distroId, int major = -1, int mino
         /// Get whether the OS platform matches the given Linux distro and optional version is same or higher.
         /// </summary>
         /// <param name="distroId">The distribution id.</param>
-        /// <param name="versionId">The distro version.  If omitted, compares the distro only.</param>
+        /// <param name="major">The distro major version.  If omitted, compares the distro only.</param>
+        /// <param name="minor">The distro minor version.  If omitted, compares the distro only.</param>
+        /// <param name="build">The distro build version.  If omitted, compares the distro only.</param>
+        /// <param name="revision">The distro revision version.  If omitted, compares the distro only.</param>
```
Comment (sharwell) [inline src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs]: 📝 These comments are not precise; same reason as previous.

File: src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj (hunk 6 above)
Comment (StanislavUshakov) [reply src/CoreFx.Private.TestUtilities/src/CoreFx.Private.TestUtilities.csproj]: Thank you, it worked. Maybe we can add it to [Advanced Build Options](https://github.com/dotnet/corefx/wiki/Build-and-run-tests#advanced-build-options) or I just wasn't able to find the right doc for it.
I will fix all Linnix / OSX / uap issues.

File: src/System.Linq/src/System.Linq.csproj [hunk 9]
```diff
@@ -3,6 +3,7 @@
     <ProjectGuid>{CA488507-3B6E-4494-B7BE-7B4EEEB2C4D1}</ProjectGuid>
     <AssemblyName>System.Linq</AssemblyName>
     <RootNamespace>System.Linq</RootNamespace>
+    <NoWarn>$(NoWarn);CS1574</NoWarn>
```
Comment (sharwell) [inline src/System.Linq/src/System.Linq.csproj]: ❕ I would prefer to see either of the following approaches:

1. Suppress CS1574 at the specific site(s) where it occurs, and not for the entire project
2. Use the ``T:Some.Namespace.ConcatIterator`1`` syntax instead of relying on the compiler to resolve the reference

Comment (StanislavUshakov) [reply src/System.Linq/src/System.Linq.csproj]: In this case I prefer the second option. Thank you for the suggestion.

File: src/Common/src/Interop/FreeBSD/Interop.Process.cs [hunk 10]
```diff
@@ -391,7 +391,7 @@ static public unsafe ProcessInfo GetProcessInfoById(int pid)
         /// <summary>
         /// Gets the process information for a given process
         /// </summary>
-        // 
+        ///
```
Comment (sharwell) [inline src/Common/src/Interop/FreeBSD/Interop.Process.cs]: 💡 It's more common to see this line removed

File: src/System.Linq/src/System/Linq/Concat.cs [hunk 11]
```diff
@@ -114,7 +114,7 @@ private sealed partial class ConcatNIterator<TSource> : ConcatIterator<TSource>
             /// </summary>
             /// <remarks>
             /// This flag allows us to determine in O(1) time whether we can preallocate for <see cref="ToArray"/>
-            /// and <see cref="ConcatIterator{TSource}.ToList"/>, and whether we can get the count of the iterator cheaply.
+            /// and <see cref="M:ConcatIterator{TSource}.ToList"/>, and whether we can get the count of the iterator cheaply.
```
Comment (sharwell) [inline src/System.Linq/src/System/Linq/Concat.cs]: ❕ This is not the correct form for this method reference. To see the correct form, you can use the following approach:

1. Restore the `cref` value to its original form
2. Compile the assembly for a target where `ConcatIterator<TSource>` is present
3. Open the output XML file and find the documentation for this member
4. Copy the qualified reference (starts with `M:`) to this location

This will produce a valid reference during UAP builds as well as non-UAP builds.

File: src/Common/src/CoreLib/System/IO/PathInternal.cs [hunk 12]
```diff
@@ -131,7 +132,9 @@ internal static string RemoveRelativeSegments(string path, int rootLength)
         /// <summary>
         /// Try to remove relative segments from the given path (without combining with a root).
         /// </summary>
+		/// <param name="path">Input path</param>
```
Comment (sharwell) [inline src/Common/src/CoreLib/System/IO/PathInternal.cs]: 😕 Unexpected mix of tabs and spaces

File: src/Common/src/Microsoft/Win32/SafeHandles/SafeHandleCache.cs [hunk 13]
```diff
@@ -18,7 +18,7 @@ internal static class SafeHandleCache<T> where T : SafeHandle
         /// <summary>
         /// Gets a cached, invalid handle.  As the instance is cached, it should either never be Disposed
         /// or it should override <see cref="SafeHandle.Dispose(bool)"/> to prevent disposal when the
-        /// instance is the <see cref="InvalidHandle"/>.
+        /// instance is the <see cref="C:InvalidHandle"/>.
```
Comment (sharwell) [inline src/Common/src/Microsoft/Win32/SafeHandles/SafeHandleCache.cs]: ❕ This is not a correct type reference. You need to fully qualify items in output form if you use a prefix. Applies to a total of three references in this file.

File: src/System.Runtime.WindowsRuntime/src/System/Runtime/InteropServices/WindowsRuntime/AsyncInfo.cs [hunk 14]
```diff
@@ -44,7 +44,7 @@ public static IAsyncAction Run(Func<CancellationToken, Task> taskProvider)
 
 
         /// <summary>
-        /// Creates and starts an <see cref="Windows.Foundation.IAsyncActionWithProgress{TProgress}"/> instance from a function
+        /// Creates and starts an <see cref="T:Windows.Foundation.IAsyncActionWithProgress{TProgress}"/> instance from a function
```
Comment (sharwell) [inline src/System.Runtime.WindowsRuntime/src/System/Runtime/InteropServices/WindowsRuntime/AsyncInfo.cs]: ❕ The qualified form uses numeric arity:

```
T:Windows.Foundation.IAsyncActionWithProgress`1
```

📝 Applies to 6 changes in this file

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.Minimal.cs [hunk 15]
```diff
@@ -147,7 +147,7 @@ internal static bool TryCopyTo<T>(this IEnumerable<T> sequence, T[] array, int a
         /// <param name="count">The number of elements in the sequence.</param>
         /// <returns>The array.</returns>
         /// <remarks>
-        /// This is more efficient than the <see cref="Enumerable.ToArray{TSource}"/> extension method
+        /// This is more efficient than the <see cref="M:Enumerable.ToArray{TSource}"/> extension method
```
Comment (sharwell) [inline src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.Minimal.cs]: ❕ This is not a correctly qualified reference

File: src/System.ComponentModel.Composition/src/Microsoft/Internal/GenerationServices.cs [hunk 16]
```diff
@@ -225,9 +223,8 @@ public static void AddLocalToLocalDictionary(this ILGenerator ilGenerator, Local
 
         /// Generates the code to get the type of an object and store it in a local
         /// <param name="ilGenerator"></param>
-        /// <param name="dictionary"></param>
-        /// <param name="key"></param>
-        /// <param name="value"></param>
+        /// <param name="exception"></param>
```
Comment (tannergooding) [inline src/System.ComponentModel.Composition/src/Microsoft/Internal/GenerationServices.cs]: I don't think I would classify this as "fixing" the suppression. It is rather working around the suppression without actually providing the documentation.

Comment (StanislavUshakov) [reply src/System.ComponentModel.Composition/src/Microsoft/Internal/GenerationServices.cs]: Definitely it's not a "fix", however there are a lot of files with such "stubs" for comments. When we remove global warning suppression from Directory.Build.props we can fine-tune these warnings on project / file level.

File: src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.Minimal.cs (hunk 15 above)
Comment (StanislavUshakov) [reply src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.Minimal.cs]: Thank you for checking reference, I will double check and update all of them.

File: src/Common/src/Microsoft/Win32/SafeHandles/SafeHandleCache.cs (hunk 13 above)
Comment (StanislavUshakov) [reply src/Common/src/Microsoft/Win32/SafeHandles/SafeHandleCache.cs]: This reference looks a tricky one as different child classes has different InvalidHandle properties:
[SafeCryptoHandles](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Security.Cryptography.Csp/src/System/Security/Cryptography/SafeCryptoHandles.cs#L93)
[SafeX509ChainHandle](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Security.Cryptography.X509Certificates/src/Microsoft/Win32/SafeHandles/SafeX509ChainHandle.cs#L19)
And there's not InvalidHandle class or struct.
We can rephrase the not to something like this:
`Gets a cached, invalid handle.  As the instance is cached, it should either never be Disposed
 or it should override <see cref="SafeHandle.Dispose(bool)"/>to prevent disposal when the instance represents an invalid handle: <see cref="C:System.Runtime.InteropServices.SafeHandle.IsInvalid"/> returns <see language="true"/>`

**Comment by StanislavUshakov** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
Thanks @StanislavUshakov . As you say, it was mislabeled. That was a lot of work!
