### PR TITLE
System.Text.Json is not inbox on netfx

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes test build break introduced by https://github.com/dotnet/corefx/commit/1743e47216aa698ffe91148f4db2078accf6030a

> Serialization\Value.ReadTests.cs(225,58): error CS0117: 'BitConverter' does not contain a definition for 'SingleToInt32Bits' [D:\a\1\s\src\System.Text.Json\tests\System.Text.Json.Tests.csproj]

https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Text.Json/tests/Serialization/Value.ReadTests.cs#L224-L227

These tests were failing on netfx, since System.Text.Json isn't inbox on that platform, but the ifdef wasn't catching that after we added `netfx` to the test configurations: https://github.com/dotnet/corefx/blame/master/src/System.Text.Json/tests/Configurations.props

CC @safern @ViktorHofer @ahsonkhan

### CODE REVIEW

**Comment by wtgodbe** [comment]
Test failures are either known outerloop issues, or known infra failures on MUSL.

**Comment by ViktorHofer** [comment]
@wtgodbe please use azp run only when you want to trigger Outerloop. In this case I guess you just wanted to retrigger CI which you can do by either push force your amended commit or retrigger via the AzDO checks page.
