### ISSUE TITLE
ARM Build Fail with System.Net.Security.Native

### ISSUE THREAD

**Issue by myungjoo** [dotnet/corefx#7090]
"pal.gssapi.cpp/h" introduced with facff9e8d04d9e7ddf53eabea365306266f48865 is creating build errors in ARM32/Linux systems:

```
[   46s] In file included from /home/abuild/rpmbuild/BUILD/corefx-0.0.1/src/Native/System.Net.Security.Native/pal_gssapi.cpp:7:
[   46s] /home/abuild/rpmbuild/BUILD/corefx-0.0.1/src/Native/System.Net.Security.Native/pal_gssapi.h:42:8: error: padding size of 'PAL_GssBuffer' with 4 bytes to alignment boundary [-Werror,-Wpadded]
[   46s] struct PAL_GssBuffer
[   46s]        ^
[   46s] [ 19%] Building CXX object System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.dir/pal_asn1_print.cpp.o
[   46s] /home/abuild/rpmbuild/BUILD/corefx-0.0.1/src/Native/System.Net.Security.Native/pal_gssapi.cpp:235:35: error: non-constant-expression cannot be narrowed from type 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
[   46s]     GssBuffer gssBuffer{.length = length, .value = buffer};
[   46s]                                   ^~~~~~
[   46s] /home/abuild/rpmbuild/BUILD/corefx-0.0.1/src/Native/System.Net.Security.Native/pal_gssapi.cpp:235:35: note: insert an explicit cast to silence this issue
[   46s]     GssBuffer gssBuffer{.length = length, .value = buffer};
[   46s]                                   ^~~~~~
[   46s]                                   static_cast<size_t>( )
[   46s] /home/abuild/rpmbuild/BUILD/corefx-0.0.1/src/Native/System.Net.Security.Native/pal_gssapi.cpp:235:35: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
[   46s]     GssBuffer gssBuffer{.length = length, .value = buffer};
[   46s]                        ~          ^~~~~~
[   46s] 3 errors generated.
```

Note that the definision of "gss_buffer_desc_struct", which defines "gssBuffer", in /usr/include/gssapi/gssapi.h,
```
typedef struct gss_buffer_desc_struct {
    size_t length;
    void *value;
} gss_buffer_desc, *gss_buffer_t;
```

May I assume that the given input, "length" is going to be within 32bit, or this relatively new module, "pal_gssapi.cpp" has forgot to support 32bit systems?

**Comment by jasonwilliams200OK** [comment]
Generally, all 64-bits data types are available on 32-bits machine.
I think changing data type to `size_t` in signature will fix this particular issue for all unices:

```diff
# src/Native/System.Net.Security.Native/pal_gssapi.cpp
@@ -227,7 +227,7 @@ extern "C" uint32_t NetSecurityNative_ReleaseCred(uint32_t* minorStatus, GssCred
     return gss_release_cred(minorStatus, credHandle);
 }
 
-extern "C" void NetSecurityNative_ReleaseGssBuffer(void* buffer, uint64_t length)
+extern "C" void NetSecurityNative_ReleaseGssBuffer(void* buffer, size_t length)
 {
     assert(buffer != nullptr);
 
# src/Native/System.Net.Security.Native/pal_gssapi.h
@@ -48,7 +48,7 @@ struct PAL_GssBuffer
 /*
 Shims the gss_release_buffer method.
 */
-extern "C" void NetSecurityNative_ReleaseGssBuffer(void* buffer, uint64_t length);
+extern "C" void NetSecurityNative_ReleaseGssBuffer(void* buffer, size_t length);
 
 /*
 Shims the gss_display_status method for minor status (status_type = GSS_C_MECH_CODE).
```

**Comment by prajwal-aithal** [comment]
I see a related error while building corefx for Linux arm32 environment (using the `arm cross` option in the build script).
```
In file included from /home/prajwal/dotnet/corefx/src/Native/System.Net.Security.Native/pal_gssapi.cpp:7:
/home/prajwal/dotnet/corefx/src/Native/System.Net.Security.Native/pal_gssapi.h:42:8: error: 
      padding size of 'PAL_GssBuffer' with 4 bytes to alignment boundary [-Werror,-Wpadded]
struct PAL_GssBuffer
       ^
1 error generated.
```
This occurs due to the size of uint8_t pointer being 4 bytes on Linux arm32.

I am able to suppress this warning using the `-Wno-padded` warning in the CMakeLists file. Is this a valid fix (suppressing all future padding warnings)?
