### PR TITLE
Remove warnings related to conflicts by updating xunit packages

### PR DESCRIPTION
**Pull request by karajas**
System.Net.Primitives and System.Net.Http tests requires an exclude compile on the version that shipped with NETStandard.Library because of a conflict with the dependencies of rtm xunit.

/cc @weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
Do you actually need a build tools version update or just the test packages?

**Comment by weshaggard** [comment]
There looks to still be a lot of warnings: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3332/console Are you going to be working on them separate from this change?

**Comment by karajas** [comment]
It requires just the test packages update, will remove the buildtoolsversion.txt update.

**Comment by karajas** [comment]
Yes this is just to clear the first chunk of warnings and then incrementally remove the others.

**Comment by karajas** [comment]
Looks like System.Net.NameResolution/tests/PalTests had an ambigious conflict with System.Net.Sockets on Unix platforms because of the following. 

>error CS0104: 'SocketType' is an ambiguous reference between 'System.Net.Internals.SocketType' and 'System.Net.Sockets.SocketType' 

I added an exclude compile on the version 4.1.0 and it returned the same number of tests.

File: src/System.Net.NameResolution/tests/PalTests/project.json [hunk 1]
```diff
@@ -24,12 +24,16 @@
     "System.Text.RegularExpressions": "4.2.0-beta-24403-05",
     "System.Threading": "4.0.12-beta-24403-05",
     "System.Threading.Tasks": "4.0.12-beta-24403-05",
+    "System.Net.Sockets": {
```
Comment (weshaggard) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: Why would you need to do an exclude compile here? Why wouldn't you just do a reference so it pulls this package version up to the higher one for the entire test project.

Comment (weshaggard) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: Can you help me understand this a little better? Is it because with your other package update we are now pulling in Sockets where we didn't before? If so I'm still not sure why that would cause a conflict. 

cc @davidsh @CIPop

Comment (karajas) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: I believe it would cause the same conflict. xunit requires a version of System.Net.Sockets since it now depends on NETStandard.Library. Before this change, the SocketType would only come from the Common file.

File: src/System.Net.Http/tests/UnitTests/project.json [hunk 2]
```diff
@@ -12,12 +12,16 @@
     "System.Reflection.TypeExtensions": "4.1.1-beta-24403-05",
     "System.Text.RegularExpressions": "4.2.0-beta-24403-05",
     "System.Resources.ResourceManager": "4.0.2-beta-24403-05",
+    "System.Net.Http": {
```
Comment (karajas) [inline src/System.Net.Http/tests/UnitTests/project.json]: @weshaggard Similar occurence here.

File: src/System.Net.Primitives/tests/FunctionalTests/project.json [hunk 3]
```diff
@@ -7,12 +7,16 @@
     "System.Runtime": "4.1.1-beta-24403-05",
     "System.Text.RegularExpressions": "4.2.0-beta-24403-05",
     "System.Threading.Tasks": "4.0.12-beta-24403-05",
+    "System.Net.Primitives": {
```
Comment (karajas) [inline src/System.Net.Primitives/tests/FunctionalTests/project.json]: @weshaggard Similar occurence in this library as well.

**Comment by karajas** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

File: src/System.Net.NameResolution/tests/PalTests/project.json (hunk 1 above)
Comment (weshaggard) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: I would expect that if you bring in the higher version directly here that would eliminate the conflict. Although I don't know where the other one is coming from. Is it coming from another package or source?

Comment (karajas) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/3181/consoleFull#1170600644a82fefab-f698-416f-8fca-58544c94cd4e

`/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Common/src/Interop/Unix/System.Native/Interop.Socket.cs(16,81): CS0104: 'SocketType' is an ambiguous reference between 'System.Net.Internals.SocketType' and 'System.Net.Sockets.SocketType' `

Comment (weshaggard) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: So I assume it was using the Internal one before your change? If so I'm good with this as a temporary workaround but please file an issue tracking the right fix for this project. I would like either @davidsh or @CIPop to suggest the best long term solution for fixing the issue.

Comment (karajas) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: Noted. I'll open issues for System.Net to remove the internals namespace or alternate solutions.

**Comment by karajas** [comment]
@dotnet-bot  test Innerloop Ubuntu14.04 Debug Build and Test please

File: src/System.Net.NameResolution/tests/PalTests/project.json (hunk 1 above)
Comment (CIPop) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: I'm not sure I understand the newly introduced issue: what was the change causing the issue?

To add some background: our PAL and UnitTests have the production code built-in by design. The design allows testing individual units instead of e2e API to avoid complicated multi-machine setup and ensure that hard to reach code is exercised.
System.Net.Internals contains types that expose more functionality compared to the ones with the same name exposed by the contracts. It is used to avoid leaking platform-specific implementation details into the public APIs and, in certain cases, to avoid cyclic dependencies between the contracts.

Comment (karajas) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: The change that I am trying to include in this PR is to use an updated version of xunit which depends on NETStandard.Library. Prior to this, we were using a version of xunit that was repackaged to restore for netstandard and did not have NETStandard.Library as a dependency. Now that xunit requires this library, it pulls down various System.Net packages at compile time. 

I think the solution here might be to actually split the tests into two projects and address the two scenarios separately.

Comment (CIPop) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: This sounds similar to the issues we're having when testing System.dll with VSTest that references System.dll.
In that case what we do is to use `#pragma warning disable 0436` to avoid the warnings. In the case of System.Net.Internal types, the ambiguity comes from having both using statements:
```
using System.Net.Internals;
using System.Net.Sockets;
```

@stephentoub @ericeil

Comment (karajas) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: Thanks @CIPop for the suggestion, currently testing a fix with the warning enabled. Am I right to assume that we require the SocketType and ProtocolType from the Net.Internals implementation as opposed to the Net.Sockets one?

Comment (CIPop) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: Yes, I believe so as those have the system-level buffers needed to perform the Win32 calls.

Comment (karajas) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: I ended up adding the following to src\Common\src\Interop\Unix\System.Native\Interop.Socket.cs and src\Common\src\System\Net\SocketProtocolSupportPal.Unix.cs 

#pragma warning disable 0436
using ProtocolType = System.Net.Internals.ProtocolType;
using SocketType = System.Net.Internals.SocketType;

File: src/System.Net.Http/tests/UnitTests/project.json (hunk 2 above)
Comment (karajas) [inline src/System.Net.Http/tests/UnitTests/project.json]: @CIPop Can you comment on the exclude compile here?

File: src/System.Net.Primitives/tests/FunctionalTests/project.json (hunk 3 above)
Comment (karajas) [inline src/System.Net.Primitives/tests/FunctionalTests/project.json]: @CIPop Also another one here

File: src/System.Net.Http/tests/UnitTests/project.json (hunk 2 above)
Comment (CIPop) [inline src/System.Net.Http/tests/UnitTests/project.json]: /cc @davidsh I think it's OK to have the exclusion here: the test is including the appropriate production files.

File: src/System.Net.NameResolution/tests/PalTests/project.json (hunk 1 above)
Comment (CIPop) [inline src/System.Net.NameResolution/tests/PalTests/project.json]: Thanks @karajas! That looks right. (of course you need to reactivate the warning after the problematic code).

File: src/System.Net.Primitives/tests/FunctionalTests/project.json (hunk 3 above)
Comment (CIPop) [inline src/System.Net.Primitives/tests/FunctionalTests/project.json]: I don't know why this would be required. The FunctionalTests should actually test the System.Net.Primitives package. 

Is this happening because xunit is using an older implementation of System.Net.Primitives?

File: src/System.Net.Http/tests/UnitTests/project.json (hunk 2 above)
Comment (davidsh) [inline src/System.Net.Http/tests/UnitTests/project.json]: >I think it's OK to have the exclusion here: the test is including the appropriate production files.

Correct.  The UnitTests bring in the product code directly as part of compiling the test assemblies themselves.  So, you should not and need not include a reference to the System.Net.Http package itself.
