### PR TITLE
Add Attribute tests in System.Runtime.InteropServices

### PR DESCRIPTION
**Pull request by hughbe**
Had these in my backlog from last week - can now send in because it won't cause merge conflicts.

The tests are pretty basic, just added for test coverage for constructors of attributes etc. etc.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet/dnceng, several failures like:
```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/dotnet/corefx
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:809)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1076)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1107)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:130)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:59)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:233)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
```

**Comment by stephentoub** [comment]
@hughbe, some of the failures are due to the PR itself, though, e.g.
```
CSC : error CS2001: Source file '/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/SecureStringMarshalTests.cs' could not be found. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.Tests.csproj]
CSC : error CS2001: Source file '/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/CurrencyWrapperTests.cs' could not be found. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.Tests.csproj]
```

**Comment by hughbe** [comment]
Ahh bad merge conflict resolution, sorry.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
Hmm `System/Runtime/InteropServices/TypeLibFuncAttributeTests.cs(15,43): error CS0246: The type or namespace name 'TypeLibFuncFlags' could not be found (are you missing a using directive or an assembly reference?) [/mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.Tests.csproj]`

**Comment by hughbe** [comment]
Same errors in UAP as on Linux.
```
18:43:51 System\Runtime\InteropServices\TypeLibFuncAttributeTests.cs(15,43): error CS0246: The type or namespace name 'TypeLibFuncFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibFuncAttributeTests.cs(12,22): error CS0246: The type or namespace name 'TypeLibFuncFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibFuncAttributeTests.cs(13,22): error CS0246: The type or namespace name 'TypeLibFuncFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibFuncAttributeTests.cs(14,21): error CS0103: The name 'TypeLibFuncFlags' does not exist in the current context [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibTypeAttributeTests.cs(15,43): error CS0246: The type or namespace name 'TypeLibTypeFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibTypeAttributeTests.cs(12,22): error CS0246: The type or namespace name 'TypeLibTypeFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibTypeAttributeTests.cs(13,22): error CS0246: The type or namespace name 'TypeLibTypeFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibTypeAttributeTests.cs(14,21): error CS0103: The name 'TypeLibTypeFlags' does not exist in the current context [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibVarAttributeTests.cs(15,42): error CS0246: The type or namespace name 'TypeLibVarFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibVarAttributeTests.cs(12,22): error CS0246: The type or namespace name 'TypeLibVarFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibVarAttributeTests.cs(13,22): error CS0246: The type or namespace name 'TypeLibVarFlags' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
18:43:51 System\Runtime\InteropServices\TypeLibVarAttributeTests.cs(14,21): error CS0103: The name 'TypeLibVarFlags' does not exist in the current context [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
```

I'm really quite confused about that.

**Comment by danmosemsft** [comment]
@hughbe I believe this is because eg TypeLibFuncFlags is not part of netstandard. (A bunch of types in S.R.IOS are in there but generally not COM related types like this). The tests\configurations.props includes netstandard, and the failure is occurring when your tests project is building for netstandard. The fix is to in your test csproj conditionally exclude source files testing non-netstandard types by doing `Condition="'$(TargetGroup)' != 'netstandard'"` on those files. 
You can built with eg /p:targetgroup=uap (or netstandard) to confirm you got it right.

**Comment by hughbe** [comment]
Test Windows x86 Release Build

**Comment by hughbe** [comment]
Test Windows x86 Release Build

**Comment by hughbe** [comment]
@stephentoub does this need a second review? No pressure of course, but I'd like to push out some changes that would conflict with this PR :)
